### ISSUE TITLE
Apply auto-naming to `resource.metadata.name`

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi-kubernetes#10]
The "name" property in Kubernetes resources is `res.metadata.name`, not `res.name` as is common in other providers.  We should consider applying our AutoNaming to this nested property.

**Comment by protometa** [comment]
Kubernetes provides a natural solution to this in the form of namespaces. There is some discussion in kubernetes/helm#2060 about the pros and cons of leveraging namespaces more directly as opposed to the the current Helm convention of prefixing names. I can see using the pulumi stack name as resource namespace as a nice default to avoid conflicts, though any default should be easy enough to override in pulumi.

**Comment by hausdorff** [comment]
I believe the right way to go is to let Pulumi handle the naming itself, and to let users encode which namespace they're deploying to inside the app code or using Kubernetes contexts (which would get picked up during `pulumi update`). But, I also believe this problem is not nearly as big a deal for the Kubernetes provider as it is for (say) the AWS provider, which is why I estimate its priority to be somewhat low compared to other issues we'd consider tackling in M16.

Mostly the reason I'd like Pulumi to handle naming is that I think namespaces are most useful as an organization construct rather than an application-level construct. So, _i.e._, different people or different teams tend to deploy to a specific namespace, RBAC is managed at the level of a specific namespace, _etc_. It seems to me to make sense to make the behavior of deploying an app to some organization's namespace really easy, rather than requiring users to boot up a new namespace for every instance of some app, especially since they might not have permission to create new namespaces at all.

That said, while I agree with @lukehoban that having Pulumi generate names would solve (a) and (c), I actually think (b) is not a huge problem for us, and this is the main reason I'd rate the priority lower. Most resources do not have a significant rollout phase (_e.g._, `ConfigMap`s, `Secret`s, _etc_., are trivially replaceable) and important resources that do (_e.g._, `Pod`s, `Pod`s attached to `PersistentVolume`s, _etc_.) tend to have built-in abstractions that handle rollout on behalf of the user (_i.e._, `Deployment` and `StatefulSet`, respectively). As I understand it, these abstractions were created to keep `kubectl` fairly lightweight, so that it didn't have to handle complicated rollout protocols. Overall I recommend we keep their strategy for ourselves.

**Comment by hausdorff** [comment]
Oh, also, this will make testing a bit easier. If we generate the names on the user's behalf, it means that by default we don't have to worry about subsequent/parallel runs trampling over or interfering with each other.

From that perspective, when you think about running a CI/CD system for an entire organization, it is clearer to me that this is actually really useful.

**Comment by hausdorff** [comment]
Fundamentally this issue involves (1) implementing autonaming, and (2) implementing correct delete-before-replace semantics.

Implementing autonaming itself amounts to appending a random suffix to an object's name -- the questions are: (1) when should we do this, (2) how, if at all, should users be allowed to manually specify a name, and (3) are there exceptions to the autonaming mechanism? To this end, I propose:

- Users should be allowed to manually specify a name for a resource (_i.e._, override autonaming) _simply by specifying `.metadata.name`_.
  - **Rationale 1:** This means we are compatible out of the box with existing YAML, which will often directly reference the names of other resources (_e.g._, `PersistentVolume`s are referenced in a Pod's volume mounts). Were we to not do this, the barrier to entry for existing apps would greatly increase.
  - **Rationale 2:** This is fairly similar to the existing `generateName` facilities of Kubernetes anyway, so it is in the parameters of something that would make sense.
  - **Rationale 3:** Helm implements autonaming as well, but every app it deploys is also a Helm chart, which is specially designed for Helm.
- `core/v1/Namespace` should be an exception.
  - **Rationale 1:** I believe most Kubernetes users would be very surprised if we auto-generated namespace names. A namespace is basically a named virtual cluster.

For delete-before-replace semantics, which are related to the override semantics, I propose:

-  We should delete-before-replace _any time we need to replace a resource and cannot autoname it_.

**Comment by hausdorff** [comment]
Also cc @lukehoban @joeduffy  ^^

**Comment by hausdorff** [comment]
Actually, thinking about this more, I think we agree that `core/v1/Namespace` should _not_ be an exception. There are two scenarios: (1) a user wants the namespace to have a specific name, and (2) a user wants a unique namespace to be generated, and for an app to be deployed to that.

Regarding @protometa's points, I think this also closes out the question of whether apps should be named uniquely, or simply deployed to new namespaces. Like Helm, at this point I believe that we should be naming the objects uniquely, as it gives us the ability to manage namespaces in Pulumi.

**Comment by lukehoban** [comment]
This proposal sounds good to me.

> Users should be allowed to manually specify a name for a resource (i.e., override autonaming) simply by specifying .metadata.name.

This is effectively the same as what we do in the terrraform-based providers.  `name` is made optional, and defaults to "pulumi name + randomness" if not specified.  This allows users to override it if they want to provide a specific name to the underlying cloud provider.  I think this should work similarly for Kubernetes.

> We should delete-before-replace any time we need to replace a resource and cannot autoname it.

This one is a little more interesting, but I think it's not a bad idea.  I'm slightly nervous about changing from "create-before-replace" to "delete-before-replace" based just on the presence of  a `metadata.name` property - but in this case we know for sure that the resource can't be successfully replaced without a "delete-before-replace", so doing that by default and proposing an actually workable update makes sense instead of just failing.

**Comment by hausdorff** [comment]
@lukehoban because delete-before-replace is so rare and fairly important, do you think we should warn the user before they're about to do a delete-before-replace?
