### ISSUE TITLE
Implement native Helm 3 support

### ISSUE THREAD

**Issue by maxromanovsky** [pulumi/pulumi-kubernetes#1051]
### Problem description

Currently Helm 2 and Helm 3 support is limited, and is based on local templating, and thus has many limitations.

I suggest adding native support for helm 3 provisioning instead of local templating.
I am not the best person to propose the implementation, but maybe it would be possible to include helm as a library, in a similar matter as kubectl includes kustomize nowadays?

Refer to existing issues: https://github.com/pulumi/pulumi-kubernetes/issues/1023, https://github.com/pulumi/pulumi-kubernetes/issues/993, https://github.com/pulumi/pulumi-kubernetes/issues/954, https://github.com/pulumi/pulumi-kubernetes/issues/1017, and in general: https://github.com/pulumi/pulumi-kubernetes/issues?q=helm

The huge limitations of existing approach for me are:
- Always running behind standard helm feature support (for instance, planned [lua support](https://github.com/helm/community/blob/master/helm-v3/000-helm-v3.md))
- Inability to leverage existing tooling around helm (i.e. dozens of plugins).

That is especially painful for managing updates to existing charts (E.g. `helm whatsup` plugin can show latest versions available for installed charts).

**Comment by lblackstone** [comment]
We've done some work towards using the Helm libraries directly within Pulumi's Kubernetes provider rather than shelling out to the `helm` binary on the user's system. However, I don't foresee us trying to integrate with Helm more deeply than our current usage (`fetch` + `template`) in either case. 

In our current model, Pulumi uses Helm to generate the initial resource definitions, and then performs any requested transformations before passing those definitions onto the Pulumi engine for CRUD management. 

It would be very difficult to integrate a standalone tool like Helm with the engine in a first-class way. Since you're using full programming languages, it's always possible to shell out to other programs if you need to, but it won't cleanly tie into the core resource model (checkpointed state, policies, auditing, etc.)

For those reasons, I'm closing this as "won't fix".

**Comment by maxromanovsky** [comment]
Understand the complexity of such solution. Let's keep this issue (closed, of course) and see if anybody 👍 it :)

@lblackstone What is the recommended solution to keep helm charts up-to-date with the current approach?

**Comment by lblackstone** [comment]
If you don't specify the [`version`](https://www.pulumi.com/docs/reference/pkg/nodejs/pulumi/kubernetes/helm/v2/#ChartOpts-version) in your `ConfigFile`/`ConfigGroup`, the latest version [1] will be deployed. However, I would recommend pinning to a specific version in your code, and update the program if/when you want to update a specific chart. At that point, you can use your tool of choice to let you know when an update is available.

[1] Note that you still have to run `helm repo update` to sync your Helm cache with upstream. This currently doesn't happen automatically in Pulumi. See #857

**Comment by maxromanovsky** [comment]
@lblackstone  Agree on pinning to specific version. Thing is, plugins such as https://github.com/fabmation-gmbh/helm-whatup don't recognize charts deployed via Pulumi
