### ISSUE TITLE
renderYamlToDirectory not exposed in Go SDK

### ISSUE THREAD

**Issue by jgrossmac** [pulumi/pulumi-kubernetes#1083]
### Problem description

It appears the Kubernetes provider option for the Go SDK does not expose the renderYamlToDirectory option.  Documentation is here for other languages: https://www.pulumi.com/blog/kubernetes-yaml-generation/

### Affected product version(s)

2.0.0

### Reproducing the issue

N/A

### Suggestions for a fix

Expose the option in the Go SDK please :)

**Comment by leezen** [comment]
This is tracked in https://github.com/pulumi/pulumi-kubernetes/issues/1037
Closing as a duplicate

**Comment by lukehoban** [comment]
FWIW - I believe this is different. That issue is about taking yaml as input and deploying with Pulumi. This is about taking Pulumi as input and deploying to YAML files. We added support for the latter in January - but looks like the option to enable it didn’t get projected into the Go Provider args.
