### ISSUE TITLE
creation failed: XXX already exists

### ISSUE THREAD

**Issue by aexei** [pulumi/pulumi-kubernetes#1224]
### Problem description

Always, when i run `pulumi up --refresh` we receive several `XXX already existing` errors.  Instead of stepping over all these deployments and services the command fails and our ci pipeline crashes.

### Errors & Logs

```
+ kubernetes:core:ServiceAccount alb-aws-alb-ingress-controller creating error: resource default/alb-aws-alb-ingress-controller was not successfully created by the Kubernetes API server : serviceaccounts "alb-aws-alb-ingress-controller" already exists
 +  kubernetes:core:ServiceAccount alb-aws-alb-ingress-controller **creating failed** error: resource default/alb-aws-alb-ingress-controller was not successfully created by the Kubernetes API server : serviceaccounts "alb-aws-alb-ingress-controller" already exists
 +  kubernetes:core:ServiceAccount default/kubernetes-dashboard creating Retry #0; creation failed: serviceaccounts "kubernetes-dashboard" already exists
 +  kubernetes:core:ServiceAccount default/kubernetes-dashboard creating error: resource default/kubernetes-dashboard was not successfully created by the Kubernetes API server : serviceaccounts "kubernetes-dashboard" already exists
 +  kubernetes:core:ServiceAccount default/kubernetes-dashboard **creating failed** error: resource default/kubernetes-dashboard was not successfully created by the Kubernetes API server : serviceaccounts "kubernetes-dashboard" already exists
```

### Affected product version(s)

2.7.1

**Comment by tmehlinger** [comment]
Same here, I am also experiencing this after updating to 2.7.1. Rolling back to 2.6.1 doesn't resolve the issue, which has me worried that there is a problem with the saved state.

**Comment by tmehlinger** [comment]
One possibility: looking at our deployment where this is happening, we had a bug where `.kube/config` wasn't being populated correctly in our Pulumi/configuration image. In the build that used our bugged image, Pulumi complained that it wasn't able to load kube configuration and failed the deployment.

Is it possible that in such a scenario, Pulumi would have written invalid state, believing the resources didn't exist?

**Comment by tmehlinger** [comment]
I've just tested this further and I have steps to reproduce. I'm using Pulumi 2.7.1 and the S3 backend.

1. Create a Pulumi stack with Kubernetes resources.
2. `up` the stack and ensure the resources exist as expected.
3. Set the `KUBECONFIG` environment variable to an invalid path.
4. `up` the stack again. Pulumi will produce errors indicating it couldn't find a valid kubeconfig file, then fail to apply configuration. _This will also write state as though the resources never existed_.
5. Reset (or unset) `KUBECONFIG` so that Pulumi can now find a valid configuration and `up` the stack again. It will attempt to create new resources, then fail when the Kuberenetes API indicates they already exist.

I was able to mitigate by deleting the resources in Kubernetes, destroying the stack, then recreating. I suspect the backup state would have been fine after a single mis-application of config. Unfortunately, I ran Pulumi multiple times trying to find the issue and didn't have a valid backup.

**Comment by sundowndev** [comment]
I have the same issue even without using --refresh option.

**Comment by lukehoban** [comment]
> up the stack again. Pulumi will produce errors indicating it couldn't find a valid kubeconfig file, then fail to apply configuration. This will also write state as though the resources never existed.

I tried to repro based on @tmehlinger's steps above with the latest provider, and could not repro this.  I know we've made some changes in this space in the last 6 months (and in particular https://github.com/pulumi/pulumi-kubernetes/pull/1522), so I'm inclined to believe this was fixed.  But if anyone still has an issue that sounds like this - and can share steps for a repro - please do let us know so we can reopen.

**Comment by pierlucg-xs** [comment]
@lukehoban I have a similar issue with 3.1.0 and believe I might have simple repro steps: https://github.com/pulumi/pulumi-kubernetes/issues/1560
