### ISSUE TITLE
When an empty / default k8s provider is used for ambient creds, it only works with ~/.kube/config not with KUBECONFIG

### ISSUE THREAD

**Issue by metral** [pulumi/pulumi-kubernetes#1252]
### Problem description

Creating a default k8s provider as such only works if `KUBECONFIG` is not set, and the kubeconfig exists at it's default location: `$HOME/.kube/config`

`const k8sProvider = new k8s.Provider("k8s");`

### Errors & Logs

Errors out trying to parse empty YAML if KUBECONFIG is used, as the provider only seems to be checking for the file `$HOME/.kube/config`

**Comment by lblackstone** [comment]
This regression was caused by #1166 

This change causes the SDKs to load the value of `KUBECONFIG`, which is a path to the file, not the contents of the file, causing the provider to fail during the Configure phase.

Rather than reverting this change, I think it makes the most sense to update the provider to handle either the contents or the path to the KUBECONFIG, and only fail with an error if both of these options fail.

Related: https://github.com/pulumi/pulumi-kubernetes/issues/1032
