### ISSUE TITLE
GRPC call to kubernetes:yaml:decode with incorrect perms on ~/.kube/config leads to confusing error

### ISSUE THREAD

**Issue by djvs** [pulumi/pulumi-kubernetes#1334]
Pulumi up to date both in project and CLI (v2.10.2)

## Expected Behavior
~/.kube/config being world-readable either warns or fails silently, doesn't produce failing error, or at least error explains what went wrong

## Current Behavior
Confusing error message that makes it sound like a helm chart is malformed

## Steps to Reproduce
Without manually doing this myself - 
1. Make a pulumi project containing a `k8s.helm.v2.Chart`
2. Set user ~/.kube/config to world-readable (chmod 555/666/777).
3. `pulumi up -y`, should fail on grpc call to kubernetes:yaml:decode

## Context (Environment)
I hit this while working on some helm charts, spent hours debugging, unable to make my project `pulumi up`.

**Comment by EronWright** [comment]
I believe that this issue is resolved, because I was unable to repro the issue using the latest provider.  I think the cause was that the provider was that the Helm CLI was emitting a warning:
```
WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: /home/username/.kube/config
```

The SDK executed `helm template` then fed the output to `kubernetes:yaml:decode` and presumably saw a parse error.
https://github.com/pulumi/pulumi-kubernetes/blob/v2.9.1/sdk/nodejs/helm/v2/helm.ts

Nowadays the provider doesn't invoke the Helm CLI, it uses Helm as a library.
