### ISSUE TITLE
`getResources` ID should understand namespacing semantics in OpenAPI spec

### ISSUE THREAD

**Issue by hausdorff** [pulumi/pulumi-kubernetes#147]
Right now the ID property is pretty dumb. It's `${namespace}/${name}` if `.metadata.namespace` is present, and `${name}` if it's not. A better approach would be to default to `default/${name}` if the resource type is "namespaced" -- _i.e._, whether OpenAPI reports that it can be deployed in a namespace.

**Comment by hausdorff** [comment]
So looking at this further, it seems that we cannot do this without consulting the API server's runtime for ever resource. In other words, for each Group/Version/Kind we must ask the API server directly: is this a namespaced resource? This makes it very, vary hard to statically implement consistent naming based on the resource type in `getResources`.

The good news is that I believe we _can_ use `pulumi.Output` to wait for `.metadata.namespace` and `.metadata.name` to resolve, which will give us what we want, as namespaced resources will be automatically granted the namespace `default` if one does not exist.

**Comment by lukehoban** [comment]
Is there anything we still plan to do here?  Sounds like we can't do the original suggestion, and have a workaround that is reasonable.

**Comment by hausdorff** [comment]
@lukehoban This would be incidentally resolved by #162. We do have to do that work, though, and it is non-trivial.

**Comment by hausdorff** [comment]
It is not super clear to me how we will actually do this. I'm assigning to @lblackstone for now, but we should discuss.

**Comment by EronWright** [comment]
To recap, the issue here is with the `getResource` method on `ConfigGroup`, how it takes the child resource name as a lookup key, and how the child resource name doesn't incorporate the default namespace.  This leads to an inconsistency in the program code.

Knowing whether a given kind is namespaced is non-trivial because CRDs aren't always available at the point where the assessment must be made to determine the resource name.  Also, we recently introduces a new version of `ConfigGroup` that doesn't have `getResources` anymore.  For these reasons, I feel it safe to close this issue as won't fix.
