### ISSUE TITLE
Add namespace to k8s CustomResource URN by default

### ISSUE THREAD

**Issue by lblackstone** [pulumi/pulumi-kubernetes#1472]
### Problem description

As a result of https://github.com/pulumi/pulumi-kubernetes/issues/1470, the user asked if it would be possible to include the namespace in k8s resource URNs by default. It does seem like this could be a potential usability improvement, but there are a few implementation details I'm unsure about.

Currently, CustomResource URNs across all Pulumi providers are derived from the `name` parameter, with no special logic to disambiguate them. This is straightforward, but can cause problems like the one in #1470 where it's unclear to the user why separately namespaced resources are getting duplicate URNs. Since URNs are an implementation detail of Pulumi, the user really shouldn't have to consider them under normal circumstances.

I think we could use aliases to avoid a breaking change related to the URN. However, resource auto-naming is also based on the `name` parameter, so we'd need to take care to avoid changing the generated `.metadata.name` of resources.

**Comment by lblackstone** [comment]
@lukehoban @pgavlin Any thoughts on this?

**Comment by almson** [comment]
> Currently, CustomResource URNs across all Pulumi providers are derived from the name parameter, with no special logic to disambiguate them.

That's not exactly true. The parents also go into the URN (specifically, the parent's type).

So, just set the parent of a resource to be a Namespace, and problem solved, right?

Well, not exactly, because only the type is included. The parent's name gets chopped off, so a namespace like

    urn:pulumi:dev::swkube::sw:KubernetesMonitoring$kubernetes:core/v1:Namespace::monitoring

creates children with URNs like 

    urn:pulumi:dev::swkube::sw:KubernetesMonitoring$kubernetes:core/v1:Namespace$kubernetes:helm.sh/v3:Chart::promtail

Nevertheless, a workaround is to create ComponentResources of different types. These will prefix to the child URNs.

**Comment by EronWright** [comment]
I feel it is safe to say that this change will not be made.  To add some color, component resources generally add their name as a prefix to the child resource names, to ensure they're unique across the stack.  This is described in [Resource Names](https://www.pulumi.com/docs/concepts/resources/names/#urns). Otherwise the names are under program control.  

It would be difficult to determine whether to include the "default" namespace, especially if the CRD isn't installed for scope discovery purposes.

**Comment by gen-xu** [comment]
is there a resolution/workaround for this? if there happens to be two k8s clusters that we want to deploy same helm chart contains CRDs, then it becomes a blocker for that.
