### ISSUE TITLE
Support for OCI helm Repositories

### ISSUE THREAD

**Issue by roitalpaz** [pulumi/pulumi-kubernetes#1477]
## Problem description
pulumi does not support using Helm chart and OCI registries with the experimental OCI support.
According to https://helm.sh/docs/topics/registries/

AWS documented the above here:
https://docs.aws.amazon.com/AmazonECR/latest/userguide/push-oci-artifact.html

**Comment by RoiSightfull** [comment]
The current workaround, download Helm chart using AWS API.

`import * as pulumi from "@pulumi/pulumi";
import {ECRClient, BatchGetImageCommand, GetDownloadUrlForLayerCommand} from "@aws-sdk/client-ecr";
import * as download from "download";

// Download and extract the `latest` helm chart into folder
export const downloadHelm = async (repoName: string, downloadDestination: string, region: string) => {
    const stampEcrClient = new ECRClient({
            region: region,
        }
    );

    const getImageCommand = new BatchGetImageCommand({
        repositoryName: repoName,
        imageIds: [{imageTag: "latest"}]
    })

    try {
        const getImagesResponse = await stampEcrClient.send(getImageCommand);
        await pulumi.log.debug(`Got ${getImagesResponse.$metadata}`)

        if (getImagesResponse.images && getImagesResponse.images.length > 0 && getImagesResponse.images[0].imageManifest) {
            if (getImagesResponse.images.length > 1) {
                await pulumi.log.error(`Got too many results. ${getImagesResponse.images.length}`)
                new pulumi.RunError(`Got too many results. ${getImagesResponse.images.length}`)
            }

            const imageManifest = JSON.parse(getImagesResponse.images[0].imageManifest)

            const getDownloadURL = new GetDownloadUrlForLayerCommand({
                repositoryName: repoName,
                layerDigest: imageManifest.layers[0].digest,
            })
            const downloadURLResponse = await stampEcrClient.send(getDownloadURL);
            if (downloadURLResponse.downloadUrl) {
                await download(downloadURLResponse.downloadUrl, downloadDestination, {extract: true});
            }

        } else {
            await pulumi.log.error(`Got no Images: ${JSON.stringify(getImagesResponse.failures)}.`)
            new pulumi.RunError("Error getting images")
        }
    } catch (error) {
        await pulumi.log.error(`Error occurred: ${JSON.stringify(error)}.`)
        new pulumi.RunError(error)
    }
}
`

**Comment by yuft** [comment]
Does anyone have a workaround for Azure Container Registry?
https://docs.microsoft.com/en-us/azure/container-registry/container-registry-helm-repos

**Comment by lblackstone** [comment]
I checked if setting the `HELM_EXPERIMENTAL_OCI` env var would work, and it doesn't appear so. It looks like we'll need to add a handler specifically for OCI repos in the client, and then create an input type to support the configuration in the SDK.

OCI support is still experimental and subject to breaking changes, but it's probably ok since we're pinning to a specific client version in the provider. The internal implementation shouldn't affect user programs as long as we can maintain the same API.

**Comment by lblackstone** [comment]
I ran into some problems trying to implement this because the required OCI client packages are still experimental:
https://github.com/helm/helm/issues/9188
https://github.com/helm/helm/issues/10393

It looks like the packages may be available to use externally sometime soon:
https://github.com/helm/helm/pull/10447

Since the upstream work is ongoing, I don't think we should directly support this feature yet. We'll keep an eye on the upstream progress, and reevaluate if it looks like it's stalled.

In the meantime, I'd suggest working around by [downloading the chart separately](https://github.com/pulumi/pulumi-kubernetes/issues/1477#issuecomment-784994737) and then referencing the local chart path.

**Comment by SharpEdgeMarshall** [comment]
With helm `3.8.x` now the OCI standard is out of beta so this issue should be reconsidered

**Comment by lblackstone** [comment]
> With helm `3.8.x` now the OCI standard is out of beta so this issue should be reconsidered

Thanks for the heads up! We'll give this another look.
