### ISSUE TITLE
Importing custom resource fails with unknown resource type error

### ISSUE THREAD

**Issue by hagaibarel** [pulumi/pulumi-kubernetes#1506]
While trying to import a `redis` custom resource to `pulumi` I'm getting an `unknown resource type` error.

## Expected behavior
Importing the resource should work

## Current behavior
Trying to import the resource via the `cli` or `json` file always results in error and failure to import.

## Steps to reproduce

1. Install [amaizfinance/redis-operator](https://github.com/amaizfinance/redis-operator) - download the `deploy` directory and run `kubectl apply -k deploy/`
2. Create an example `redis` instance - `kubectl apply -f https://raw.githubusercontent.com/amaizfinance/redis-operator/master/example/k8s_v1alpha1_redis_cr.yaml`
3. Try to import to `pulumi` - `pulumi import kubernetes:k8s.amaiz.com/v1alpha1:Redis example example`

Always throws the same error:

```shell
Previewing import (dev):
     Type                                        Name       Plan       Info
     pulumi:pulumi:Stack                         redis-dev             1 error
 =   └─ kubernetes:k8s.amaiz.com/v1alpha1:Redis  example    import     1 error
 
Diagnostics:
  kubernetes:k8s.amaiz.com/v1alpha1:Redis (example):
    error: Preview failed: unknown resource type 'kubernetes:k8s.amaiz.com/v1alpha1:Redis'
 
  pulumi:pulumi:Stack (redis-dev):
    error: preview failed
```

This seems to happen just on import. While using `crd2pulumi` and creating a programmatic instance of `redis`, `pulumi` is able to create and manage the resource just fine.

`pulumi` version - `v2.23.1`
`pulumi-kubernetes` - `2.8.3`
`go` - `1.16.2`

**Comment by komalali** [comment]
@lblackstone any quick ideas what might be going on here? Is it that `import` can only import resources defined within the pulumi schema?

**Comment by lblackstone** [comment]
> Is it that import can only import resources defined within the pulumi schema?

That would be my guess. I can't think a reason it shouldn't work in theory, but it would require extra logic for k8s CustomResources. I expect the part that's failing is the code-generation since the k8s provider doesn't have knowledge about the custom schema. This case seems fairly tricky to support, but the `crd2pulumi` tool includes most of the logic that would be required.

**Comment by HagaiBarel** [comment]
@lblackstone if this is caused by the code generation preview, is it possible to skip it during import? For example in the form of some flag for the `import` command

**Comment by lblackstone** [comment]
As far as I know, this isn't possible currently. I think you could still manually import the resource using the [import](https://www.pulumi.com/docs/reference/pkg/nodejs/pulumi/pulumi/#CustomResourceOptions-import) option on the resource rather than using the `pulumi import` command. [This blog post](https://www.pulumi.com/blog/adopting-existing-cloud-resources-into-pulumi/#adopting-existing-resources) gives an example of this for a different resource type.

**Comment by HagaiBarel** [comment]
Can confirm that using that using the `import` option on the resource allows to import the resource properly to `pulumi`. Thanks for the help @lblackstone.

I would still love to see it working using the `cli` but programmatic `import` is a good solution as well
