### ISSUE TITLE
No resource plugin kubernetes found in path

### ISSUE THREAD

**Issue by bradkyle** [pulumi/pulumi-kubernetes#1562]
Trying to run pulumi preview fails (unfixable?)

)pulumi preview
...
>    error: no resource plugin 'kubernetes-v5.2.0' found in the workspace or on your $PATH, install the plugin using `pulumi plugin install resource kubernetes v5.2.0`

)pulumi plugin install resource kubernetes v5.2.0
>[resource plugin kubernetes-5.2.0] installing
error: [resource plugin kubernetes-5.1.0] downloading from : 403 HTTP error fetching plugin from https://get.pulumi.com/releases/plugins/pulumi-resource-kubernetes-v5.2.0-linux-amd64.tar.gz

)pulumi plugin install resource kubernetes v5.1.0
>[resource plugin kubernetes-5.1.0] installing
error: [resource plugin kubernetes-5.1.0] downloading from : 403 HTTP error fetching plugin from https://get.pulumi.com/releases/plugins/pulumi-resource-kubernetes-v5.1.0-linux-amd64.tar.gz

package.json (dependencies):
  ```
"dependencies": {
    "@pulumi/docker": "^3.0.0",
    "@pulumi/gcp": "^5.2.0",
    "@pulumi/kubernetes": "^3.0.0",
    "@pulumi/pulumi": "^3.0.0",
    "@pulumi/random": "^4.0.0", 
  }

```
I have tried pulumi plugin rm --alll etc.
How does one mitigate this?
Thanks
 
1.
2.
3.
4.

**Comment by bradkyle** [comment]
Any ideas on this? I still have not found a solution

**Comment by justinvp** [comment]
@bradkyle, what version of the Pulumi CLI are you using (e.g. `pulumi version`)? It is odd that it is trying to install v5.2.0 of the kubernetes plugin since the latest version is v3.1.0.

Is this an existing stack or a new stack?

If you run `pulumi preview --logtostderr -v=9`, the initial log lines for `plugins.go` and `langruntime_plugin.go` may provide some insight on what plugins it thinks are needed for the program.

**Comment by lukehoban** [comment]
It appears that the version for GCP (`v5.2.0`) is being used for Kubernetes.  I recall we fixed a bug in the last few months that could lead to this - though I'm having trouble finding the specific fix we took.  I believe this should be fixed in the latest Pulumi CLI releases.
