### ISSUE TITLE
Unable to use StorageClassArgs, ClusterRoleArgs, ClusterRoleBindingArgs

### ISSUE THREAD

**Issue by Slaiyer** [pulumi/pulumi-kubernetes#1571]
Unable to use second constructor from [here](https://www.pulumi.com/docs/reference/pkg/kubernetes/storage/v1/storageclass/#create) with `StorageClassArgs`.

Call site looks like:
```
pulumi_kubernetes.storage.v1.StorageClass(
            resource_name='string',
            args=pulumi_kubernetes.storage.v1.StorageClassArgs(...),
            opts=pulumi.ResourceOptions(...),
)
```

## Expected behavior
Should work the same as constructor 1, which is what I'm currently using as a workaround.

## Current behavior
Same issue with `ClusterRole` and `ClusterRoleBinding` as well:
```
File ".../venv/lib/python3.9/site-packages/pulumi_kubernetes/storage/v1/StorageClass.py", line 237, in __init__
        __self__._internal_init(resource_name, *args, **kwargs)
    TypeError: _internal_init() got an unexpected keyword argument 'args'
```

## Steps to reproduce
1. `pulumi-kubernetes==3.1.1`, all other libs up to date as well
2. `pulumi up`

## Context (Environment)
Trying to define a `StorageClass` in Azure AKS for use with Azure Files.

## Affected feature
`pulumi-kubernetes`

**Comment by justinvp** [comment]
We recently added the resource constructor overload that accepts an args class named `<Resource>Args`. The problem is that some providers (Kubernetes, Azure Native, and Google Native) have some input types and resources with the same name, which results in two different `<Resource>Args` classes in the same module.

When you try to use `args=pulumi_kubernetes.storage.v1.StorageClassArgs(...)`, you're actually referring to the existing `StorageClassArgs` input type rather than the intended new resource args class, which results in an error due to the type mismatch.

AFAIK, this hasn't broken usage of the existing `StorageClassArgs` input type because we "export" all the input types from `_inputs` _after_ all the resource and resource args classes (which is why you get the input type above rather than the resource args class):

https://github.com/pulumi/pulumi-kubernetes/blob/4a9faee0aeb374af4308265e361a7af30bc9b8ca/sdk/python/pulumi_kubernetes/storage/v1/__init__.py#L7-L17

To address this, we can fix the Python SDK code generator to emit the resource args class with an alternate name, such as `<Resource>InitArgs` when an input type named `<Resource>Args` exists in the module. Technically, renaming the type is a breaking change, but since this functionality is so new and since the way one would try to import it is broken anyway, it seems worth doing.

The best workaround in the meantime is to use the constructor overload that accepts keyword arguments instead.

Not recommended: It is possible to import the args class where it is defined via `from pulumi_kubernetes.storage.v1.StorageClass import StorageClassArgs` and pass an instance of it to the `StorageClass` resource's constructor overload for `args`, but I would avoid doing this since we're very likely going to rename this `StorageClassArgs` class to address this issue.
