### ISSUE TITLE
Cannot use `Input<>` with `ChartOpts`

### ISSUE THREAD

**Issue by pgavlin** [pulumi/pulumi-kubernetes#162]
e.g. the outputs of another resource cannot be used to fill in a Helm chart's parameters.

**Comment by hausdorff** [comment]
This turns out to be harder than we had thought -- `chart.values` needs to be recursively expanded before it is written to some temporary file, so that the `helm` CLI can pick it up. Let's move to 0.18, as this will not block adoptino.

**Comment by hausdorff** [comment]
Let's expand the scope of this issue to make all `ChartOpts` of type `pulumi.Input`

**Comment by hausdorff** [comment]
Let's be sure to resolve #147 as part of this.

**Comment by joeduffy** [comment]
@hausdorff Any progress on this?

**Comment by hausdorff** [comment]
After some consideration, @lukehoban and I now believe that _any_ approach that requires any subset of `ChartOpts` fields to be `Input<T>` will break `preview`. We believe there is no remediation for this problem, and we believe this flaw is serious enough to not proceed with this feature.

Our reasoning:

* We need to call `pulumi.output` on `ChartOpts` before we shell out to the `helm` CLI in order to resolve all the values that we'd pass to the Chart.
* This implies that `Chart#resources` needs to be type `Output<T>`, since in general we have no ability to statically determine what resources will be output by `helm`'s template expand without running it on the fully-resolved values.
* This, in turn, implies that `preview` could (and, we believe, very often will) generate a preview that is drastically different from what will be executed, as we are essentially generating those resources inside a call to `.apply`.

At the same time, we believe this issue will come up a lot, so I'll be playing around with some other ideas about how we can smooth this flow out in the near future.

I'll leave the issue open for other input.

**Comment by pgavlin** [comment]
Fixed in #241.
