### ISSUE TITLE
Secrets are updated not replaced

### ISSUE THREAD

**Issue by nesl247** [pulumi/pulumi-kubernetes#1667]
I updated a `Secret`, and it was `updated` not `replaced`. I am using the server side apply functionality if that helps. This actually triggered a bug for us as we expected the `Deployment` to be updated but wasn't.

_Originally posted by @nesl247 in https://github.com/pulumi/pulumi-kubernetes/issues/1568#issuecomment-892857395_

**Comment by lblackstone** [comment]
Interesting -- I confirmed that this is specific to the SSA diff, and works as expected with the default client-side diff behavior. Still investigating.

**Comment by lblackstone** [comment]
The bug appears to be specific to the way we're computing replacements for Secret and ConfigMap. Both of these resources contain fields (`stringData` and `data` respectively) that are processed server-side to update related fields (`data` and `binaryData` respectively). The SS diff shows a different field being patched in this case, which led to the bug.

I'm working on a fix now, but it also works properly if you update the `data` field on the Secret rather than the `stringData` field.
