### ISSUE TITLE
Move all Helm related features to another repo

### ISSUE THREAD

**Issue by mingfang** [pulumi/pulumi-kubernetes#175]
Please keep this repo pure Kubernetes and move all Helm related features to another dedicated repo.

**Comment by hausdorff** [comment]
Thanks for opening the discussion! It seems to me that most of our prospective users are probably using Helm now, and so rather than asking them to install two things, it makes sense to me to bundle them together. I do agree this makes the repository less pure.

What do you see as the main negative impacts that would cause us to want to change this decision?

**Comment by mingfang** [comment]
I don't agree but I can fork this repo to remove it myself.

**Comment by joeduffy** [comment]
I agree with Ming on this.

One repo to do one thing well.

**Comment by joeduffy** [comment]
And more importantly, one package per major component.

**Comment by joeduffy** [comment]
Helm is an independent project with independent governance, and lifetime. I love Helm, but I'd be incredibly surprised if there is 80% overlap. Our overall policy elsewhere is to keep opinionated policy out of the core fundamental repos, particularly during "incubation," and that applies here also.

If the Helm project ever merges with Kubernetes in a more intimate way, we can revisit, but for now, we should move it out into its own package. The fact that the API isn't yet settled is even more reason to move it out soon, as we rapidly approach a reasonable "1.0" release of the core Kubernetes package.

**Comment by mingfang** [comment]
I agree with @joeduffy completely.
In fact I feel the concept of awaiters here is also opinionated and should be opted in.
But that's battle for another ticket :-)

**Comment by hausdorff** [comment]
So, again, to summarize: I am ok if you and @lukehoban agree to move this out, but I do want to be very clear about what I think the implications are (creates a road block for most of our at-scale users, which we know from previous experience is significant because of discoverability problems) and why I think it is not so far-fetched to glom it in (because it is a part of what people think about when they think about the kube API).

I think at this point you and @lukehoban have the information you need to know to make the decision, but you two disagree. I am not particularly attached to either outcome, all I care about is that we all have the same information as input. If you do care a lot, you two should go off and decide. :)

**Comment by joeduffy** [comment]
Let's wait and see where we land on repo structure for all our Kubernetes work in flight.

**Comment by hausdorff** [comment]
I think we should commit to this for the Q3 march. It's easy, it allows us document Helm support totally separately (a big win), it insulates the k8s provider versioning from the major changes that are about to happen in Helm 3, it provides a nice place to keep all the Helm issues, it lets us talk about k8s and Helm maturity independently, it frees us to write a dedicated Helm provider, and so on.

**Comment by lblackstone** [comment]
Helm support is now implemented using invokes into the k8s provider, and we also manage Kustomize and YAML in this repo, so I'm closing this out as "won't fix".
