### ISSUE TITLE
`Error: unknown provider ''` when default provider disabled

### ISSUE THREAD

**Issue by ncsibra** [pulumi/pulumi-kubernetes#1912]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

Disabling the default kubernetes provider generates an `Error: unknown provider ''` error with `k8s.helm.v3.Chart`.

pulumi cli version: v3.24.1
pulumi-kubernetes version: v3.16.0

Pulumi.dev.yaml:
```
config:
  pulumi:disable-default-providers:
  - kubernetes
```

index.ts:
```
import * as k8s from '@pulumi/kubernetes'

const k8sProvider = new k8s.Provider(`k8s-provider`, {
  kubeconfig: '/home/ncsibra/.kube/dliver_dev',
})

new k8s.helm.v3.Chart(
  'cert-manager',
  {
    repo: 'jetstack',
    chart: 'cert-manager',
    version: 'v1.5.3',
  },
  {
    provider: k8sProvider,
  }
)
```

pulumi up:
```
     Type                            Name                Plan       Info
 +   pulumi:pulumi:Stack             k8s-cert-manager-dev  create     1 error
 +   ├─ kubernetes:helm.sh/v3:Chart  cert-manager        create
 +   └─ pulumi:providers:kubernetes  k8s-provider        create

Diagnostics:
  pulumi:pulumi:Stack (k8s-cert-manager-dev):
    error: Error: unknown provider ''
        at Object.callback (/home/ncsibra/dev/prmrgt-infra/pulumi/node_modules/@pulumi/runtime/invoke.ts:161:33)
        at Object.onReceiveStatus (/home/ncsibra/dev/prmrgt-infra/pulumi/node_modules/@grpc/grpc-js/src/client.ts:338:26)
        at Object.onReceiveStatus (/home/ncsibra/dev/prmrgt-infra/pulumi/node_modules/@grpc/grpc-js/src/client-interceptors.ts:426:34)
        at Object.onReceiveStatus (/home/ncsibra/dev/prmrgt-infra/pulumi/node_modules/@grpc/grpc-js/src/client-interceptors.ts:389:48)
        at /home/ncsibra/dev/prmrgt-infra/pulumi/node_modules/@grpc/grpc-js/src/call-stream.ts:276:24
        at processTicksAndRejections (node:internal/process/task_queues:78:11)
```

**Comment by viveklak** [comment]
This is indeed because of the way the helm component resources invoke the template-generation invoke function in the provider. We have managed to get away with this so far because we set the version resource opt here: https://github.com/pulumi/pulumi-kubernetes/blob/master/sdk/nodejs/helm/v3/helm.ts#L229 which implicitly ends up using the default provider. With the addition of the disable default provider option, this provider is no longer available.

I am dropping P1 since it is not broadly applicable. I have fixes for the various language implementations in the meantime and will update with a reference to a PR.
