### ISSUE TITLE
v1.Secret recreated on every run when applying transformation to password input

### ISSUE THREAD

**Issue by f11r** [pulumi/pulumi-kubernetes#1954]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

When creating a `v1.Secret` using a `RandomPassword` with a transformation function, the secret is recreated on every run. Without the transformation function (`generate_htpasswd` in the example) the behavior is as expected: the secret is created once and then not changed unless the actual password changes. Is this expected behavior? If yes, is there a way to work around it?

### Steps to reproduce

```
    import crypt

    import pulumi_random as random
    import pulumi_kubernetes as k8s

    password = random.RandomPassword("pass", length=128)

    def generate_htpasswd(password_str):
        pwhash = crypt.crypt(password_str)
        return f"username:{pwhash}"

    secret_auth = k8s.core.v1.Secret(
        "basic-auth",
        string_data=dict(auth=password.result.apply(generate_htpasswd)),
        metadata=dict(namespace=namespace),
        opts=pulumi.ResourceOptions(provider=cluster, parent=namespace),
    )
```

Expected: The secret should be created once and not change unless `password.result` changes
Actual: The secret is recreated on every run `+-  kubernetes:core/v1:Secret                basic-auth                                replace     [diff: +stringData]`

**Comment by viveklak** [comment]
This is expected since `crypt.crypt` will salt and generate a new value every time it is run.

One option here might be to consider a [`dynamic provider`](https://www.pulumi.com/docs/intro/concepts/resources/dynamic-providers/) to model a resource which salts the password resource (but as its a resource, it only changes if the password changes). See https://www.pulumi.com/docs/intro/concepts/resources/dynamic-providers/#example-random for an example. Hope this helps!

**Comment by f11r** [comment]
That makes sense. Will take a look at the dynamic providers.
