### ISSUE TITLE
Helm Chart Fails to Deploy

### ISSUE THREAD

**Issue by pauljrob** [pulumi/pulumi-kubernetes#1967]
When deploying the GitLab Helm chart on EKS the deployment hangs. If I run the same chart manually from Helm directly, it works just fine.

## Expected Behavior
GitLab Helm chart should deploy just like I can from Helm CLI.

## Current Behavior
Pods fail to start, Pulumi hangs.

## Steps to Reproduce
Try running this: 

```ts
const gitlab = new k8s.helm.v3.Chart("gitlab-server", {
    chart: "gitlab",
    fetchOpts:{
        repo: "https://charts.gitlab.io/",
    },
    values: {
        "certmanager-issuer": {
            email: "admin@mydomain.com",
        },
        global: {
            hosts: {
                domain: "mydomain.com",
            },
        },
    }
});
```

## Context (Environment)

I'm going to have to use Helm to install GitLab which is fine but ideally I keep all my IaC in one place. This also makes me hesitant to use Pulumi's Helm support because I'm unsure why this is failing.

**Comment by lblackstone** [comment]
This works out of the box if you use the `helm.v3.Release` resource rather than `helm.v3.Chart`. [This guide](https://www.pulumi.com/registry/packages/kubernetes/how-to-guides/choosing-the-right-helm-resource-for-your-use-case/) explains the differences between the two resource types.

```ts
const gitlab = new k8s.helm.v3.Release("gitlab-server", {
    chart: "gitlab",
    repositoryOpts: {
        repo: "https://charts.gitlab.io/",
    },
    skipAwait: true, // Shouldn't be needed if you use valid values for email/domain
    values: {
        "certmanager-issuer": {
            email: "admin@mydomain.com",
        },
        global: {
            hosts: {
                domain: "mydomain.com",
            },
        },
    }
});
```
![Screenshot 2023-07-14 at 12 21 41 PM](https://github.com/pulumi/pulumi-kubernetes/assets/9253463/3648ef95-dc17-4217-b178-cd00fcd4ff0e)
