### ISSUE TITLE
Pulumi Helm Release not following Helm values precedence

### ISSUE THREAD

**Issue by jlabedo** [pulumi/pulumi-kubernetes#1986]
Following https://helm.sh/docs/chart_template_guide/values_files/, values provided to the chart come from multiple sources, in this order:

> - The values.yaml file in the chart
> - If this is a subchart, the values.yaml file of a parent chart
> - A values file if passed into helm install or helm upgrade with the -f flag (helm install -f myvals.yaml ./mychart)
> - Individual parameters passed with --set (such as helm install --set foo=bar ./mychart)

With Pulumi, setting `valueYamlFiles` and `values` in the same Release resource seems to give precedence to `valueYamlFiles` instead of `values` map.

The issue may be fixed by changing the order of the parameters in :
https://github.com/pulumi/pulumi-kubernetes/blob/eff06344d7f9f0d862d7f63e8aae252253fb5af9/provider/pkg/provider/helm_release.go#L302
with : `release.Values, err = mergeMaps(values, release.Values)`

**Comment by erwen** [comment]
@jlabedo Did you find a way to fix this? I have the same issue

**Comment by danielrbradley** [comment]
[Here's some notes I made on why this is broken](https://github.com/pulumi/pulumi-kubernetes/issues/2188#issuecomment-1256442951). I think the fix is as simple as [reversing the arguments in the provider call](https://github.com/pulumi/pulumi-kubernetes/blob/3c1b35cb3e183d572f374ff28b0505c4e412464c/provider/pkg/provider/helm_release.go#L307).
