### ISSUE TITLE
`helm template --namespace` appears to do nothing

### ISSUE THREAD

**Issue by hausdorff** [pulumi/pulumi-kubernetes#200]
This means that our template expansion does not respect the `--namespace` flag as we had hoped.

**Comment by hausdorff** [comment]
Ah, when @pgavlin and I chatted about this, we discovered that `--namespace` actually populates `.Release.namespace`. This makes sense for them, as they'll want to be able to manage multi-namespace Charts, but it's different from `kubectl`, where `--namespace` will simply put all objects that can be namespaced and are being `apply`'d, into some namespace.

We can close this.

**Comment by geekflyer** [comment]
question regarding k8s helm integration: 
When I specify `namespace` on a chart via pulumi it seems this only populates the `Release.Namespace` template variable, whereas when running `helm install --namespace <namespace>` tiller seems to actively add an `metadata.namespace` entry before applying the templates to the cluster. Many charts unfortunately don’t have the `Release.Namespace` variable but instead rely on the aforementioned tiller override. Would it be possible to add a similar behaviour to the pulumi helm integration? I think that would greatly decrease confusion for users. I can probably for now manually apply the desired namespace by using `transformations` but I think it would be better UX if pulumi helm behaves a little more like `helm install` instead of `helm template`.

**Comment by geekflyer** [comment]
Here's an example transformation that works for me:

```
const namespace = 'mycustomns';

const rabbitmq = new k8s.helm.v2.Chart('rabbitmq', {
  repo: 'stable',
  version: '2.2.0',
  chart: 'rabbitmq',
  namespace,
  transformations: [
    manifest => {
      manifest.metadata.namespace = namespace;
    }
  ]
});
```

**Comment by geekflyer** [comment]
created a dedicated gh issue for my request: #217
