### ISSUE TITLE
Error message for partial `Deployment` rollout could be better

### ISSUE THREAD

**Issue by hausdorff** [pulumi/pulumi-kubernetes#208]
If a user does a `kubectl scale` to scale their app up, ` pulumi refresh` will error until the rollout is complete. In general we should write out "application in the process of a rollout" instead of the following:

```
pulumi refresh --diff
Previewing refresh of stack 'k8s-dev'
Previewing changes:
* pulumi:pulumi:Stack: (same)
    [urn=urn:pulumi:k8s-dev::k8s::pulumi:pulumi:Stack::k8s-k8s-dev]
[MinimumReplicasUnavailable] Deployment does not have minimum availability.
Preview failed: 3 errors occurred:

* Resource 'nginx-07olkcrj' was created but failed to initialize
* [MinimumReplicasUnavailable] Deployment does not have minimum availability.
* Minimum number of live Pods was not attained
error: an error occurred while advancing the preview
```

**Comment by lblackstone** [comment]
Working on cleaning up the Deployment awaiter, so this won't be done before M21

**Comment by lblackstone** [comment]
This work will follow completion of #451 
Moving to M22

**Comment by hausdorff** [comment]
One thing to keep in mind here is: some (many?) users see these issues and are confused about whether they're Pulumi's fault or not. A good test of whether we've succeeded is whether that's true anymore.

**Comment by ellismg** [comment]
Sorry - Dumb question here.  I believe elsewhere we had discussed not running awaiters during `refresh` (or at least not treating them as things that could fail the overall operation).  Does that impact this issue here?

I think there may be two things conflated here:

1. An in progress rollout blocks `pulumi refresh` from completing.
2. The message when you hit this state is confusing.

Do our plans to change the interaction of awaiters with refresh mean that (1) is no longer an issue?  If so, does that mean (2) is OK?

**Comment by lblackstone** [comment]
Just tested, and wasn't able to reproduce (1), so (2) is not relevant for this case. I'll close out this issue for now, and will reconsider all of our error messages on the next refactoring pass.

Unfortunately, I seem to have uncovered a different bug: https://github.com/pulumi/pulumi-kubernetes/issues/694
