### ISSUE TITLE
Can't rollout Deployment in Helm Chart via ConfigMap data change

### ISSUE THREAD

**Issue by clark1013** [pulumi/pulumi-kubernetes#2091]
### What happened?

As the document（https://www.pulumi.com/registry/packages/kubernetes/how-to-guides/kubernetes-ts-configmap-rollout/ ）mentioned，Pulumi can rollout Deployment via ConfigMap data change. But this feature does not works properly if the Deployment is in the Helm Chart.

### Steps to reproduce

I use kong helm chart and load plugins, it can reproduce this bug.

### Expected Behavior

Deployment rollout

### Actual Behavior

Deployment does not rollout

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by viveklak** [comment]
@clark1013 thanks for opening the issue. Could you check if you are using the [Helm Release ](https://www.pulumi.com/registry/packages/kubernetes/api-docs/helm/v3/release/)resource instead of the helm Chart resource?

**Comment by clark1013** [comment]
@viveklak Thanks for your reply. I am using the Helm Chart resource but it doesn't work for me. `const kong = new k8s.helm.v3.Chart(`

**Comment by viveklak** [comment]
@clark1013 could you share a bit more of your code? How are you updating the configmap if it is installed via the helm chart? Are you making the change manually (kubectl)? Pulumi will only roll out changes if the helm chart template expansion applies the change. The more details you are able to share about your workflow and code the more useful it would be.

**Comment by clark1013** [comment]
OK, I will make a demo to show this problem this weekend. Thank you.

**Comment by clark1013** [comment]
https://github.com/clark1013/practices/tree/main/pulumi
@viveklak Hi, I have made a demo for this issue. You can clone the repo or just copy some files to reproduce the issue. PTAL.
1. Create a stack then run `pulumi up`
2. make some changes in the plugin files `handler.lua`, the plugin is loaded via ConfigMap. https://github.com/clark1013/practices/blob/main/pulumi/demo-myheader/handler.lua
3. Run `pulumi up` again. Then you can see the ConfigMap is changed but the Deployment `kong-kong` doesn't rollout.

```
➜  pulumi git:(main) ✗ pulumi up
Previewing update (test):
     Type                             Name              Plan        Info
     pulumi:pulumi:Stack              pulum-test
 +-  └─ kubernetes:core/v1:ConfigMap  kong-plugin-demo  replace     [diff: ~data]

Resources:
    +-1 to replace
    16 unchanged

Do you want to perform this update? no
confirmation declined, not proceeding with the update
```

**Comment by clark1013** [comment]
@viveklak Hi, Could you please take a look at this?

**Comment by viveklak** [comment]
@clark1013 thanks for the code example! The key to the triggered rollout in our how-to guide is the use of "autonaming" in the config map and the reference to the "autonamed" configmap in the deployment spec: https://github.com/pulumi/examples/blob/master/kubernetes-ts-configmap-rollout/index.ts#L40.

Because the configmap doesn't have an explicit name, a random name is assigned at initial creation. The deployment spec references the configmap name in its spec. Later when the configmap is changed, the provider "recreates" the configmap assigning a new name which also propagates a change to the deployment spec resulting in a replacement there. In cases where the resources are autonamed the provider will implicitly create new resources before deleting the previous resource causing the safe rollout.

In your example you are explicitly naming the configmap. In this case during a replacement due to a change to the configmap, the provider will try to retain the same provided name, resulting in a deletion of the configmap first followed by the creation of the replacement preserving the name. In this case, since the deployment spec never changed, the rollout never happens. Would you be able to remove the name here: https://github.com/clark1013/practices/blob/main/pulumi/index.ts#L19 and reference the name in the deployment spec indirectly through the `demoPlugin` resource?

**Comment by clark1013** [comment]
I understand, I will have a try, thank you very much for your patience
