### ISSUE TITLE
When should we make use of pulumi.com/patchFieldManager?

### ISSUE THREAD

**Issue by rshade** [pulumi/pulumi-kubernetes#2119]
### What happened?

What is the current use-case for `pulumi.com/patchFieldManager`? When reviewing the docs here: https://www.pulumi.com/registry/packages/kubernetes/how-to-guides/managing-resources-with-server-side-apply/#delete-an-existing-field-using-patch, it is unclear, if it should be multiple - uuids. We have tested with the following example code, and it doesn't `seem` to work, whereas it works without it: 

```typescript
// const uuid1 = "47201079-2760-495C-98B9-BF64572A4446"; // Arbitrary UUID
const ds1 = new k8s.apps.v1.DaemonSetPatch(
    "add-kube-proxy-label",
    {
        metadata: {
            name: "kube-proxy",
            namespace: "kube-system",
            annotations: {
                // "pulumi.com/patchFieldManager": uuid1,
            },
            labels: {
                "pulumi.com/patchForce": "true",
                "test-label-key": "test-label-value",
            },
        },
    },
    { provider: k8sProvider },
);

// const uuid2 = "47201079-2760-495C-98B9-BF64572A4447"; // Arbitrary UUID
const ds2 = new k8s.apps.v1.DaemonSetPatch(
    "add-kube-proxy-label-2",
    {
        metadata: {
            name: "kube-proxy",
            namespace: "kube-system",
            annotations: {
                "pulumi.com/patchForce": "true",
                // "pulumi.com/patchFieldManager": uuid2,
            },
            labels: {
                "test-label-key-2": "test-label-value-2",
            },
        },
    },
    { provider: k8sProvider },
);

const ds3 = new k8s.apps.v1.DaemonSetPatch(
    "add-kube-proxy-label-3",
    {
        metadata: {
            name: "kube-proxy",
            namespace: "kube-system",
            labels: {
                "test-label-key-3": "test-label-value-3",
            },
        },
        spec: {
            template: {
                spec: {
                    containers: [
                        {
                            name: "kube-proxy",
                        },
                    ],
                },
            },
        },
    },
    { provider: k8sProvider },
);
```

### Steps to reproduce

1. Use the code above and uncomment the uuid's. 

### Expected Behavior

It should work the same as without the field, but with new tracking ids's

### Actual Behavior

This is more of an advisory ticket. 

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by lblackstone** [comment]
I tested this, and it seems to work as I'd expect, with or without the fieldManager being specified explicitly. I will update the documentation to be clearer about when to set the fieldManager explicitly, but here's the summary:

In most cases, you shouldn't need to set the fieldManager value. The provider automatically assigns a unique fieldManager name to each resource by default. There are currently two use cases that I know of for setting the fieldManager directly:

1. Transferring ownership of a field to a different manager. This could apply in cases where you want to relinquish management of a field that is currently managed by Pulumi to another controller.
2. Deleting an existing field from a resource. This is the case [documented in the example that you linked](https://www.pulumi.com/registry/packages/kubernetes/how-to-guides/managing-resources-with-server-side-apply/#delete-an-existing-field-using-patch). The key part of that example is first taking ownership of the field, and then setting it to null/undefined in a subsequent patch. These two parts need to use the same fieldManager, which is the purpose of the explicit UUIDs (otherwise the two patches would get different values automatically assigned, which doesn't work for the delete case here). By first taking ownership of the field, and then setting it to null/undefined, the field will be deleted. Note that the example assumes that the `.labels.foo` value exists prior to applying these patches.

I'll leave this issue open for now and close it once I've updated the docs with this info, but I believe this is working as expected.
