### ISSUE TITLE
Get k8s api return invalid apiVersion client.authentication.k8s.io/v1alpha1

### ISSUE THREAD

**Issue by dlrudwns135** [pulumi/pulumi-kubernetes#2160]
### What happened?

At some point, this problem occurs and I don't know the cause.

Get k8s api return invalid apiVersion client.authentication.k8s.io/v1alpha1 when i run `pulumi up`

I just want make role and role binding for specific resources.

### Steps to reproduce

use cli version following.
 - kubectl: 1.23.6
 - eks: 1.21
 - aws cli: 2.2.32
 - pulumi: 3.39.1

use sdk version
 - pulumi sdk: 3.16.0
 - pulumi k8s sdk: 3.21.1

### Expected Behavior

I expect make role and role binding.

### Actual Behavior

I get error
` error: failed to initialize discovery client: exec plugin: invalid apiVersion "client.authentication.k8s.io/v1alpha1"`

### Output of `pulumi about`

CLI          
Version      3.39.1
Go Version   go1.19
Go Compiler  gc

Host     
OS       darwin
Version  12.3.1
Arch     arm64

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by gunzy83** [comment]
I have run into this same error message and have solved the issue in our case (not without serious pain). Could you post your project structure and package versions? Are you using yarn workspaces?

**Comment by dlrudwns135** [comment]
@gunzy83 No, i use golang. I update content of pulumi about.

**Comment by dlrudwns135** [comment]
@gunzy83 what is your problem cause the error?

**Comment by viveklak** [comment]
Are you using the [pulumi-eks component](https://github.com/pulumi/pulumi-eks) to create the cluster? Are you sure you are using v1.23.6 of `kubectl`? That version should be able to consume the v1alpha1 version. As described in https://github.com/pulumi/pulumi-eks#pre-requisites - we recommend using kubectl 1.24.0 and v2.7.0 of the aws-cli. Are you working against an older cluster perhaps which had its kubeconfig set with the v1alpha1 endpoint? Posting a portion of the kubeconfig would also help identify the issue here.

**Comment by dlrudwns135** [comment]
No, I don't use pulumi-eks component, i just use eks component in pulumi-aws. And i sure to use v1.23.6 of kubectl. 
![image](https://user-images.githubusercontent.com/6123435/188765329-2d91c5b9-d7c4-47b0-a18d-bb1656c75d0c.png)
![image](https://user-images.githubusercontent.com/6123435/188765374-5a026f8a-80e2-4953-aa32-cf2718818587.png)

And i use package 
![image](https://user-images.githubusercontent.com/6123435/188765696-388b3069-adda-417a-9a75-b65001844e55.png)

**Comment by viveklak** [comment]
Thanks @dlrudwns135 - could you share a bit of your code? In particular, how you are generating the kubeconfig? 

If you are using code borrowed/inspired from this example: https://github.com/pulumi/examples/blob/master/aws-go-eks/main.go - then the code to generate the kubeconfig [here](https://github.com/pulumi/examples/blob/master/aws-go-eks/main.go#L226) would need some updates to use the v1beta1 endpoint instead. Contrast the above against the code here: https://github.com/pulumi/pulumi-eks/blob/master/nodejs/eks/cluster.ts#L186. If you are interested, we would gladly take a contribution to the above example code to use the new endpoint instead.

**Comment by dlrudwns135** [comment]
I use kubeconfig template when make kubeconfig following:
![image](https://user-images.githubusercontent.com/6123435/188787241-e896e504-c898-436b-9eca-6c1cf88f2d63.png)

**Comment by viveklak** [comment]
OK in which case you will want to replace the use of `client.authentication.k8s.io/v1alpha1` with v1beta1. I still don't know why your kubectl `1.23.6` is not able to find the v1alpha1 api version. But regardless, for your stack to be future proof you will want to switch to using the v1beta1 api version anyway.

**Comment by dlrudwns135** [comment]
@viveklak Yes, i agreee, however, not now. Because, i have live service and latest version of aws eks is 1.23.7
So, It cannot apply now.

**Comment by viveklak** [comment]
OK. Perhaps you can consider rolling further back on your kubectl version? (make sure if you are running this in a CI environment that the version is what you'd expect). If 1.23.6 isn't working, try moving further back to 1.21.9 or something. Unfortunately this is just a side-effect of how EKS does its authentication and not an issue with the provider etc.

**Comment by dlrudwns135** [comment]
@viveklak Oh, it resolved. I downgrade kubectl to v1.22.1.

**Comment by gunzy83** [comment]
@viveklak Our issue was largely caused by user error with yarn workspaces and package resolution issues (inheriting a repo maintained part time by a mix of engineers). Though based on my testing with various `kubectl` versions between `1.21` and `1.25` and seeing the pulumi cli demand a much later resource plugin than specified in our state, I can only assume there are some operations the kubernetes resource plugin performs with `client-go` and not `kubectl`. Is that correct? Not sure if it is related to the problem here but how does pulumi decide the versions of resource plugins to download?

Once I got the dependencies in order and the `@pulumi/eks` node module was no longer building a kubeconfig with `v1alpha1` everything came good.
