### ISSUE TITLE
Kubernetes YAML ConfigGroupArgs and ConfigFileArgs to Accept Inputty Types

### ISSUE THREAD

**Issue by phillipedwards** [pulumi/pulumi-kubernetes#2203]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details
Currently, `ConfigGroupArgs` and `ConfigFileArgs` accept prompt values only which does not work when you have a non-prompt value(s) aka `pulumi.Input | pulumi.Output`.

**Comment by phillipedwards** [comment]
https://www.pulumi.com/registry/packages/kubernetes/api-docs/yaml/configgroup/#properties

**Comment by lblackstone** [comment]
For historical context, the prompt value requirement was to improve previews since you couldn’t tell what would be provisioned otherwise. If you need to use Inputty types with the YAML, Helm, or Kustomize SDKs, I’d suggest wrapping those resources in an apply. 

This will likely be addressed in the future by rewriting these resources as Multi-language Components, or similar. The following issues are related:
https://github.com/pulumi/pulumi-kubernetes/issues/1971
https://github.com/pulumi/pulumi-kubernetes/issues/2181

**Comment by phillipedwards** [comment]
Thank's for the context @lblackstone.

**Comment by EronWright** [comment]
This feature is available now with the new "v2" implementations, enjoy!
https://www.pulumi.com/blog/kubernetes-yaml-v2/
