### ISSUE TITLE
Setting resource_version on ClusterRole to string throws error: error: `strconv.ParseUint: parsing "example-clusterrole": invalid syntax`

### ISSUE THREAD

**Issue by rshade** [pulumi/pulumi-kubernetes#2351]
### What happened?

Setting resource_version on ClusterRole to string throws error: error: `strconv.ParseUint: parsing "examle-clusterrole": invalid syntax`. The type is set to str in https://github.com/pulumi/pulumi-kubernetes/blob/master/sdk/python/pulumi_kubernetes/meta/v1/_inputs.py#L1013

### Expected Behavior

Unsure, either it should type check early or possibly a better error message. 

### Steps to reproduce

```
ClusterRole(
            resource_name="example-clusterrole",
            metadata=ObjectMetaArgs(
                resource_version="example-clusterrole",
                name="kube-system:example"
            ),
            rules=[
                PolicyRuleArgs(
                    api_groups=[""],
                    resources=["namespaces", "pods"],
                    verbs=["get", "list", "watch"],
                )
            ],
        )
```

### Output of `pulumi about`

kubernetes    3.24.2

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by kpitzen** [comment]
Hey @rshade ! Looking at this issue, it appears the API spec for K8s requires this to be a `string` input, but that input must also be parsable as an integer (which is unfortunate). I'd consider this an enhancement to existing behavior, rather than a but, but I agree we should improve the experience to make this more clear. What would your preferred behavior be? I'm not sure we can change the type annotations for this as an argument, as that would require special-casing at the schema layer, but maybe that's something we could explore. It would be a relatively smaller change to make the error message more clear (we're parsing from string to unsigned int, so adding prose to the effect of "Please provide a string which can be converted to an integer").

**Comment by rshade** [comment]
@kpitzen Yeah, its definitely some unfortunate kube behavior. I think if we throw the error during parsing, it should be fine, instead of when the kube client does it. Its very difficult from that error to discern where the problem is.

**Comment by lblackstone** [comment]
The `resourceVersion` field should be read-only. We may need to update this type in our schema to reflect that.

> An opaque value that represents the internal version of this object that can be used by clients to determine when objects have changed. May be used for optimistic concurrency, change detection, and the watch operation on a resource or set of resources. Clients must treat these values as opaque and passed unmodified back to the server. They may only be valid for a particular resource or set of resources. Populated by the system. Read-only. Value must be treated as opaque by clients

https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.25/#objectmeta-v1-meta

**Comment by EronWright** [comment]
Related to the read-only aspect, bear in mind that the resource version is the basis for optimistic concurrency, and an update or patch request may specify it.
