### ISSUE TITLE
Rendering Kubernetes YAML to directory with render_yaml_to_directory in Python is not compatible with KUBECONFIG environment variable

### ISSUE THREAD

**Issue by matusnovak** [pulumi/pulumi-kubernetes#2535]
### What happened?

If you have the following environment variable set (to any value):

```
export KUBECONFIG=/etc/rancher/k3s/k3s.yaml
```

and you are using:

```py
provider = Provider("k8s-yaml-rendered", ProviderArgs(
    render_yaml_to_directory="yaml",
))
```

it will result in the following error:

```
Diagnostics:
  pulumi:providers:kubernetes (k8s-yaml-rendered):
    error: pulumi:providers:kubernetes resource 'k8s-yaml-rendered': property kubeconfig value {/etc/rancher/k3s/k3s.yaml} has a problem: "kubeconfig" arg is not compatible with "renderYamlToDirectory" arg
```

Setting the `kubeconfig` arg in `ProviderArgs` does not help.

The only thing that helps is to un-set or set the environment variable `KUBECONFIG` to an empty value:

```
export KUBECONFIG=
```

### Expected Behavior

The `pulumi up` should not error due to the `kubeconfig` when `render_yaml_to_directory` is set.

### Steps to reproduce

Minimal example:

```py
import pulumi_kubernetes as kubernetes

provider = kubernetes.Provider("k8s-yaml-rendered", kubernetes.ProviderArgs(
    render_yaml_to_directory="yaml",
))
```

Steps to reproduce:

```
export KUBECONFIG=/etc/rancher/k3s/k3s.yaml
pulumi up
```

### Output of `pulumi about`

```
CLI          
Version      3.75.0
Go Version   go1.20.5
Go Compiler  gc

Plugins
NAME        VERSION
kubernetes  3.30.2
python      unknown

Host     
OS       arch
Version  "23.0.0"
Arch     x86_64

This project is written in python: executable='/usr/bin/python3' version='3.11.3
'

Current Stack: organization/energise/homelab

Found no resources associated with homelab

Found no pending operations associated with homelab

Backend        
Name           threadripper-desktop
URL            file://~
User           mnovak
Organizations  

Dependencies:
NAME               VERSION
click              8.1.6
pip                22.3.1
pulumi-kubernetes  3.30.2
pydantic           2.0.3
setuptools         65.5.1
wheel              0.38.4

Pulumi locates its logs in /tmp by default
```

### Additional context

Relevant to: https://github.com/pulumi/pulumi-kubernetes/issues/1025

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by rquitales** [comment]
Hello @matusnovak,

Thank you for reporting this issue, and we apologize for the inconvenience you're encountering. After a thorough review of this beta feature, it has become clear that the intention is to allow either specifying a live Kubernetes cluster or enabling YAML rendering support. However, presenting both options to the provider results in an error, as it's challenging to determine whether the user intends to apply resources to the cluster or just render YAML resource manifests.

Consequently, the provider specifically checks for the presence of three other fields at the provider level: `cluster`, `context`, or `kubeconfig`. If any of these fields are set, a conflicting fields error is triggered ([link to code](https://github.com/pulumi/pulumi-kubernetes/blob/51b89923978bec388e563c5c88c00359ceacd115/provider/pkg/provider/provider.go#L296-L316)).

It's unlikely that we will modify this behavior. Additionally, instead of unsetting the environment variable, you can also set it to an empty value in `ProviderArgs` as an alternative approach to avoid the conflicting fields error. For instance:

```python
provider = kubernetes.Provider("k8s-yaml-rendered", kubernetes.ProviderArgs(
    render_yaml_to_directory="yaml", kubeconfig="",
))
```

We appreciate your understanding, and please feel free to reach out if you have any more questions or concerns. Your contributions and feedback are valuable as we continue to improve our services.

Thank you for your patience, and we're committed to ensuring a smoother experience for you moving forward.

**Comment by xunleii** [comment]
For those of you reading this issue and using Typescript, specifying `kubeconfig: ""` as a provider argument is not enough to avoid this problem, as conditional checking checks whether `kubeconfig` is truthy (aka non-empty string) rather than checking whether it is undefined (https://github.com/pulumi/pulumi-kubernetes/blob/master/sdk/nodejs/provider.ts#L48).

A simple but dirty workarround is to delete the environment in the Pulumi program prior instanciating the `Provider`.

For exemple
```typescript
delete process.env.KUBECONFIG
const provider = new Provider("kubernetes", {renderYamlToDirectory: ...});
```

> [!NOTE]
> The _must_ should be to fix it inside the SDK but, as is it an experimental argument and the file is generated by `pulumigen`, I think it is not worth to try to fix it
