### ISSUE TITLE
Support explicitly passing --kube-version to helm 

### ISSUE THREAD

**Issue by henry-fn** [pulumi/pulumi-kubernetes#2563]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

https://github.com/pulumi/pulumi-kubernetes/issues/753 explained this issue well, but the resolution does not cover one edge case that we cared about. We have a workflow where we would like to run previews without access to the actual K8s API server (just based on pulumi state which IIUC in the case of helm charts should only use helm template). 

https://github.com/pulumi/pulumi-kubernetes/issues/753#issuecomment-875148955 asked for a way to explicitly set `kubeVersion` in the helm args which would have solved our issue as we can explicitly pass this value when running in this semi-offline mode, however the [resolution](https://github.com/pulumi/pulumi-kubernetes/issues/196) to the previous issue was to auto-derive it from the server which doesn't work in our case. Could a `kubeVersion` argument still be added to the helm release / chart options to allow explicit override in these cases?

### Affected area/feature

helm
sdk

**Comment by henry-fn** [comment]
Mistakenly put a `closes` comment in my fork's MR

**Comment by hypesystem** [comment]
Did this make it into Releases to, or just Chart? I'm seeing the same issue using an imported Release, and am not familiar enough with the code here to understand what it affects :smile:

**Comment by EronWright** [comment]
I believe the fix was developed for `Chart` only. @rquitales I am re-opening this to consider a fix for `Release`.

**Comment by hypesystem** [comment]
If there is anything I can help with (including writing code), please let me know, and I'll be happy to contribute in any way I can to help move it forward :smile:

**Comment by hypesystem** [comment]
I've been looking into the code, and adding KubeVersion seems like it would be pretty straight-forward. I've noticed that the automatic discovery of api versions and kubeversion is also only implemented for chart, and not release.

This has lead to my confusing situation of importing a release from a running cluster, that now cannot be previewed or upped because the validation assumes a wrong kubeVersion (from local helm install).

I think it would make sense to try and align the two, maybe even reuse some common code for the templating in the two cases, to minimize the risk of them diverging in the future?

**Comment by omidraha** [comment]
I think I have related issue when I use `pulumi` to install `longhorn` by  `helm`  chart on 'k3s' : 
https://github.com/longhorn/longhorn/issues/4788#issuecomment-1792937587

I don't have this issue when I use helm command to install `longhorn` on 'k3s`'

**Comment by EronWright** [comment]
@omidraha see https://github.com/pulumi/pulumi-kubernetes/issues/2631

**Comment by EronWright** [comment]
As of pulumi-kubernetes v4.5.4 (https://github.com/pulumi/pulumi-kubernetes/pull/2653), any problem with "chart requires kubeVersion" should be fixed, except in the special case that there's a server connectivity problem, e.g. due to a bad provider configuration.

I see no way to pass an explicit `kubeVersion` to Helm during the create or upgrade operation; Helm always uses the server version. Such a feature seems to make sense only for offline templating, i.e. using `Chart` resource. For that reason, I am closing this issue as complete.

**Comment by hypesystem** [comment]
@EronWright Really nice work! Thank you :smile:
