### ISSUE TITLE
Could add containers to a pod managed by a statefulset, but could not remove them

### ISSUE THREAD

**Issue by mohitreddy1996** [pulumi/pulumi-kubernetes#2595]
### What happened?

Without knowing the restriction that adding or removing containers in PodSpec of a Statefulset or Deployment is not allowed, I ended up adding new containers to a statefulset. 

Did a pulumi up which resulted in each pod of the statefulset having configured number of containers.

Later we wanted to revert this change due to an application level bug. Pulumi would not detect that the containers in podspec are being removed. That's when we read the documentation to see the limitation. 

[EDIT] - We had to manually remove the containers using `kubectl edit` and later do a `pulumi refresh`

Question - Why does pulumi not allow adding/removing containers? Are there plans to add support for this?

### Example

Pulumi diff when we were able to add containers

```
~ kubernetes:apps/v1:StatefulSet: (update)
        [id=prod/engine]
        [urn=urn:pulumi:tier-140::launchpad::kubernetes:apps/v1:StatefulSet::engine-statefulset]
        [provider=urn:pulumi:tier-140::launchpad::pulumi:providers:kubernetes::tier-k8s-provider::bc61ac30-8bcd-45e0-b69d-e52f0c5783ee]
      ~ spec: {
          ~ template: {
              ~ spec: {
                  ~ containers: [
                      ~ [0]: {
                              ~ command     : [
                                  ~ [0]: "/root/engine" => "/root/py"
                                  ... [redacted] ...
                            }
                      + [1]: {
                              + command        : [
                              +     [0]: "/root/py"
                                ..... [redacted] ...
                            }
                      + [2]: {
                              + command        : [
                              +     [0]: "/root/py"
                         .... [redacted] ....
```

We removed these added containers in the follow up and saw no modifications to the statefulset.

Even added `replaceOnChanges: ["spec.template.spec.containers"]` to the statefulset definition but that didn't help as well.

### Output of `pulumi about`

```
pulumi about
CLI
Version      3.86.0
Go Version   go1.21.1
Go Compiler  gc

Plugins
NAME        VERSION
aws         5.42.0
cloudflare  5.11.0
command     0.5.2
docker      3.6.1
eks         0.40.0
kafka       3.5.0
kubernetes  3.30.2
nodejs      unknown
postgresql  3.10.0
random      4.14.0
tls         4.11.0

Host
OS       darwin
Version  13.5.2
Arch     arm64

This project is written in nodejs: executable='/nix/store/k99j8cjbrj7gafxc1bzvj2n9pbxh2581-nodejs-18.16.0/bin/node' version='v18.16.0'

Current Stack: fennel/launchpad/tier-140

TYPE                                           URN
xxx [redacted]


Found no pending operations associated with tier-140

Backend
Name           pulumi.com
URL            https://app.pulumi.com/mohitreddy1996
User           mohitreddy1996
Organizations  mohitreddy1996, fennel
Token type     personal

Dependencies:
NAME                VERSION
ts-node             10.9.1
@pulumi/random      4.14.0
@types/jsbn         1.2.31
@pulumi/postgresql  3.10.0
@pulumi/pulumi      3.86.0
@types/netmask      1.0.30
typescript          4.9.5
vitest              0.33.0
@pulumi/aws         5.42.0
@pulumi/kubernetes  3.30.2
@pulumi/kafka       3.5.0
@pulumi/tls         4.11.0
immer               10.0.3
@pulumi/cloudflare  5.11.0
@pulumi/docker      3.6.1
cidr-tools          6.4.2
netmask             2.0.2
ts-md5              1.3.1
@pulumi/command     0.5.2
@pulumi/eks         0.40.0

Pulumi locates its logs in /tmp by default
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by rquitales** [comment]
Hello @mohitreddy1996,

Thank you for bringing this to our attention, and I apologize for the issue you're encountering. I'd like to clarify that Pulumi does support updating containers within a pod template, despite the information in our documentation.

For context, Kubernetes has certain restrictions when it comes to updating the list of containers in a Pod resource. Pods are designed to be disposable and replaceable, as outlined in the Kubernetes documentation [here](https://kubernetes.io/docs/concepts/workloads/pods/ephemeral-containers/#understanding-ephemeral-containers). Therefore, Kubernetes users are encouraged to manage Pods using higher-level resources like Deployments, StatefulSets, DaemonSets, or ReplicaSets. By using these resources to manage Pods, you can indeed update the pod template to add or remove containers as needed. The deployment controller (or equivalent) will take care of deleting and replacing Pods to ensure they match the desired state and intended containers.

Regarding our documentation stating that containers cannot be updated within Deployments, StatefulSets, DaemonSets, or ReplicaSets (e.g., [here](https://www.pulumi.com/registry/packages/kubernetes/api-docs/core/v1/pod/#containers_nodejs)), this is due to the fact that the PodTemplateSpec API type is the same type as the PodSpec Type. You can find more details in the official Kubernetes API documentation [here](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.28/#pod-v1-core). This results in the PodTemplateSpec documentation stating that updating containers is not supported, which isn't entirely true since the deployment controller (or equivalent) will handle updating the pods.

Returning to your original issue, I attempted to reproduce it locally but was unable to do so. I successfully added a container to an existing StatefulSet using Pulumi and then removed that added container in a subsequent `pulumi up` run.

I noticed that you're using version 3 of our Kubernetes provider. Could you please try updating to version 4 to see if it resolves the issue you're facing?

Thank you for your patience and cooperation as we work to address this matter. If you have any further questions or encounter additional issues, please don't hesitate to reach out.

**Comment by mohitreddy1996** [comment]
Thanks a lot for a detailed response @rquitales . I upgraded the kubernetes provider to 4.2.0 and things worked :)
