### ISSUE TITLE
Field is immutable error when Helm updates CSIDriver

### ISSUE THREAD

**Issue by Aetf** [pulumi/pulumi-kubernetes#2620]
### What happened?

I'm deploying juicefs-csi-driver via helm, When running a new deployment Pulumi is issuing an update to the CSIDriver definition and k8s responds with `podInfoOnMount` field is immutable error. This should be fixable by using a replace.

### Example

* First have [juicefs-csi-driver](https://togithub.com/juicedata/juicefs-csi-driver) ([source](https://togithub.com/juicedata/charts)) helm chart version `0.13.5` installed
* Update to `0.18.1` version

Run `pulumi up --yes`

### Output of `pulumi about`
```
  kubernetes:storage.k8s.io/v1:CSIDriver (csi.juicefs.com):
    error: 1 error occurred:
        * the Kubernetes API server reported that "csi.juicefs.com" failed to fully initialize or become live: CSIDriver.storage.k8s.io "csi.juicefs.com" is invalid: spec.podInfoOnMount: Invalid value: true: field is immutable
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by rquitales** [comment]
Hello @Aetf,

Thank you for bringing this issue to our attention. It seems that you are using the `kubernetes.helm.v3.Chart` resource in your scenario. It's important to note that the Chart resource does not support Helm lifecycle hooks. These hooks are essential for the juicefs Helm chart to manage resource replacement due to field immutability. The error you are encountering when trying to update to version v0.18.1 is a result of this, as the Chart resource converts Kubernetes resources into individual resources within the Pulumi program.

To address this issue, we recommend considering the use of the `kubernetes.helm.v3.Release` resource instead. This resource will enable you to upgrade from v0.13.5 to v0.18.1 without running into the immutability error. I have personally tested both resources and can confirm that using the Release resource helps mitigate this problem.

For more information about these two resources, you can refer to this discussion on GitHub: [GH Issue response](https://github.com/pulumi/pulumi-kubernetes/issues/555#issuecomment-1647187595) and this informative blog post that provides additional details about the Release resource: [Blog Post](https://www.pulumi.com/blog/full-access-to-helm-features-through-new-helm-release-resource-for-kubernetes/).

If you have further questions or need additional assistance, please don't hesitate to reach out.
