### ISSUE TITLE
Allow a model similar to `kubectl apply -f`

### ISSUE THREAD

**Issue by hausdorff** [pulumi/pulumi-kubernetes#264]
In Kubernetes it is somewhat common to use {`kubectl apply -f`, `kubectl patch`, _etc_.} to update system resources after they have been created. For example, to update default `ServiceAccount` roles in an EKS cluster after it's been created. (_cf_., [this community issue](https://github.com/pulumi/pulumi/issues/1691).)

There isn't really anything like this in Pulumi. We offer `.get` to retrieve the resources and track them in the statefile, but we offer no ability to change them.

In the medium term we can expose creation hooks, which would allow us to shell out to `kubectl` to update such resources on EKS creation (_cf_., https://github.com/pulumi/pulumi/issues/1691), but in the longer term it is likely that we'll want to solve the general problem of patching system resources that you didn't create.

One idea is to use a system of _overlays_:

* Expose something like `core.apps.v1.Deployment.get(...).update([... deployment literal ...])`
* The semantics of this are as follows:
  * If this is the first time we're `get`'ing the resource (_i.e._, we can think of this as a "create", but with an existing resource), then we'll take the live object, and do the normal update operation. What gets stored in the checkpoint file is (1) blank previous inputs, (2) the original live object, and (3) the "current inputs". Under `pulumi destroy`, we'll probably need to "undo" any updates, so we should hang on to the live object. More on this below.
  * If this is and subsequent update, we'll simply apply the update operation between (1) the last `update` args, (2) the current live object, and (3) the new `update` args.
  * If this is a `pulumi destroy`, we'll want to probably "undo" all of this entirely, and put the object back in the state it was before we touched it. In particular we do _not_ want to delete the whole object, or at least, not by default. In the case of system resources this is potentially catastrophic.

Thoughts? cc @pgavlin @lukehoban @joeduffy

**Comment by hausdorff** [comment]
Another idea is to call it `.patch` instead of `.update` and keep track of the current patch instead of the whole object.

Also worth noting that we probably don't want to expose `update` on any old `CustomResource`, but really just the ones we're returning from `.get`.

**Comment by gitfool** [comment]
I need support for read-modify-write / patch of existing resources. My use cases so far:
- Patch KubeProxy & CoreDNS version (https://github.com/pulumi/pulumi-eks/issues/253):
```sh
kubectl set image -n kube-system daemonset.apps/kube-proxy kube-proxy=602401143452.dkr.ecr.us-west-2.amazonaws.com/eks/kube-proxy:v1.14.6
kubectl set image -n kube-system deployment.apps/coredns coredns=602401143452.dkr.ecr.us-west-2.amazonaws.com/eks/coredns:v1.3.1
```
- Patch KubeProxy metrics bind address  for prometheus ([prometheus-operator#kubeproxy](https://github.com/helm/charts/tree/master/stable/prometheus-operator#kubeproxy))
```sh
kubectl -n kube-system edit cm kube-proxy
# metricsBindAddress: 0.0.0.0:10249
```
These sorts of things need to be captured for automatic rollout.

**Comment by lukehoban** [comment]
We added a `kubectlReplace` endpoint in https://github.com/pulumi/pulumi-kubernetes/pull/579.  I'm not sure that's quite what's needed here - but it's similar - and we may want to use a similar approach.

**Comment by lblackstone** [comment]
I actually removed the replace functionality awhile back because it didn't turn out to be very helpful. The main problem was that it was asynchronous, and didn't do any readiness checking.

It is possible to use Pulumi's import functionality to edit existing resources, but the process is a bit heavy:

1. Import existing resource
1. `pulumi up` to import
1. Make desired changes to imported resource
1. `pulumi up` to apply changes

Ideally, we should support simple edits in a single step to make this easy to accomplish in CI. 
I like the original overlay suggestion as long as it's a synchronous method that includes readiness checks.

This might look something like:
```ts
core.apps.v1.Deployment.get("coredns").patch({
    image: "602401143452.dkr.ecr.us-west-2.amazonaws.com/eks/coredns:v1.3.1"
})
```

**Comment by gkonc001** [comment]
I'm currently trying to find something similar to `kubectl patch deployment` and I was wondering if a feature like that is/was implemented.

**Comment by lblackstone** [comment]
@gkonc001 The feature I described hasn't been implemented yet. Can you tell me more about your use case?

**Comment by gkonc001** [comment]
@lblackstone Yes, I currently have a spring cloud data flow chart that uses grafana monitoring and I'm trying to do something similar to `kubectl patch deployment grafana --patch "$(cat ./kubernetes/grafana-deployment.yaml)"` to the helm chart using the grafana-deployment.yaml file.

**Comment by davzucky** [comment]
@lblackstone I have a requirement as well for that feature.
I'm looking at this feature to be able to use the digital ocean registry for any image. From the doc you need to update the default profile
[https://www.digitalocean.com/docs/images/container-registry/quickstart/](https://www.digitalocean.com/docs/images/container-registry/quickstart/)
```kubectl patch serviceaccount default -p '{"imagePullSecrets": [{"name": "registry-<my-registry>"}]}'```

**Comment by Sodki** [comment]
My use case is to update the configuration of CoreDNS, which comes pre-installed on EKS. I have two options:

1. Either use `kubectl patch` to update the configuration
2. Use `kubectl apply` with a YAML file provided by AWS, which can also be used to upgrade the version of CoreDNS

So, reading through other people's messages, it seems we need both an `apply` and a `patch`.

Personally I would like for an apply to be able to override existing objects, but the result would be resources managed by Pulumi.

**Comment by jwenz723** [comment]
Without this feature being available, would the current suggested way of using pulumi to do something like patching the kube-proxy container image be to use Dynamic Providers to wrab the standard kubernetes libraries?

**Comment by lblackstone** [comment]
> Without this feature being available, would the current suggested way of using pulumi to do something like patching the kube-proxy container image be to use Dynamic Providers to wrab the standard kubernetes libraries?

Yes, using a dynamic provider around a native k8s client is a good way to handle this.

**Comment by gitfool** [comment]
@lblackstone I'd love to see a specific example, if there isn't one already.

Also, more generally, is it looking like there will be a way to write dynamic providers in other languages like .NET/C#? What's the status of the current experiments? Sorry to keep pressing this issue but it's become clear it's really important for lots of little things.

**Comment by Slaiyer** [comment]
> > Without this feature being available, would the current suggested way of using pulumi to do something like patching the kube-proxy container image be to use Dynamic Providers to wrab the standard kubernetes libraries?
> 
> Yes, using a dynamic provider around a native k8s client is a good way to handle this.

Can we have sample code for this?
I'm looking to patch the default serviceaccount of a given namespace with image pull secrets.

**Comment by clstokes** [comment]
Here's an [example of doing kubectl apply -f from a DynamicProvider in TypeScript](https://github.com/pulumi/examples/blob/258d3bad0a00020704743e37911c51be63c06bb4/aws-ts-eks-distro/eksdistro/index.ts#L69-L70). Note, that provider also does some `kops` commands so it would need to be adjusted for this specific case.

**Comment by farvour** [comment]
I would like to see a feature like this. When EKS creates clusters, it's common for someone to want to edit/patch/change something about the default installed `kube-proxy` or `coredns` without having to full-blown manage it in Pulumi. This allow allows for a bit of idempotent when a new cluster is spun up without having to cover for all the semantics of changes on the object I don't care about (the image tag, for example, changes from EKS version to EKS version for kube-proxy).

**Comment by gitfool** [comment]
@farvour I'm hoping https://github.com/aws/containers-roadmap/issues/1159 will help in this specific case, although it looks a little rough around the edges.

Meanwhile, I'm still holding out that .NET/C# dynamic providers will be [available soon](https://github.com/pulumi/pulumi/issues/3638#issuecomment-760101712).

**Comment by steve-marmalade** [comment]
@lblackstone , thank you for your suggested workaround.  Can you provide an example command of the form `pulumi import [type] [name] [id]` that will import an existing kubernetes resource?

**Comment by davidroth** [comment]
I am also interested in this. I need to update/patch an existing kubernetes ConfigMap.
My use case: After setting up a new AWS EKS cluster, I have to [configure the aws-auth config map](https://docs.aws.amazon.com/eks/latest/userguide/add-user-role.html) and add a `mapUsers` section to the existing configmap.
Thats not possible atm so I need a separate manual pipeline step which calls "kubectl apply -f" for this :-/

**Comment by gitfool** [comment]
@davidroth for that particular case you can avoid needing to patch the `aws-auth` config map by creating it _before_ any node groups (which should explicitly depend on the `aws-auth` resource since it's not passed to any input).

**Comment by farvour** [comment]
> @farvour I'm hoping [aws/containers-roadmap#1159](https://github.com/aws/containers-roadmap/issues/1159) will help in this specific case, although it looks a little rough around the edges.
> 
> Meanwhile, I'm still holding out that .NET/C# dynamic providers will be [available soon](https://github.com/pulumi/pulumi/issues/3638#issuecomment-760101712).

An interesting feature to be sure. Although, I feel this adds yet another complexity layer to EKS. I've mulled it over since I wrote my original comment on the matter, and I feel like the dynamic providers and then rolling our own self-managed coredns and kube-proxy would have better long-term efficacy unless AWS can make this eks addons feature seamless during upgrades. Some of the major pain points I'm seeing in _that_ thread is that the addons manager wants to enforce its own configuration on top of Corefile and other things. Things that dynamic or partial resource providers in Pulumi can solve for me and I don't have to rely on AWS's version.

**Comment by davidroth** [comment]
> @davidroth for that particular case you can avoid needing to patch the `aws-auth` config map by creating it _before_ any node groups (which should explicitly depend on the `aws-auth` resource since it's not passed to any input).

Thanks for the hint. That made me re-evaluate the options when creating the EKS cluster via pulumi. Fortunately, there are already `userMappings` and `roleMapping` properties available when creating a cluster via "pulumi/eks".

Example:
```typescript
new eks.Cluster(name, {
    vpcId: vpc.id,
    .....
    userMappings: // <--- When setting mappings here, auth-config is configured during cluster creation
    roleMappings // <---- When setting mappings here, auth-config is configured during cluster creation
});
```
Exactly what I was looking for 🚀

**Comment by alex-hunt-materialize** [comment]
Adding another example, for setting the `AWS_VPC_K8S_CNI_EXTERNALSNAT` on the `aws-node` daemonset in an EKS cluster.

```
kubectl set env daemonset -n kube-system aws-node AWS_VPC_K8S_CNI_EXTERNALSNAT=true
```

This is made much worse by dynamic providers being broken in python when outside of `__main__` https://github.com/pulumi/pulumi/issues/7453

**Comment by jordiprats** [comment]
For what's worth, there's also a discussion on the terraform side on how to implement this: [issue-723](https://github.com/hashicorp/terraform-provider-kubernetes/issues/723)

**Comment by leshibily** [comment]
> 

@lblackstone @clstokes  was this implemented? I have a use to patch coredns tolerations when I have taints set for all my nodes.

**Comment by lblackstone** [comment]
> @lblackstone @clstokes was this implemented? I have a use to patch coredns tolerations when I have taints set for all my nodes.

I haven't tried it myself yet, but we recently added the `pulumi/command` provider, which might fit your needs here. The [Kubernetes example](https://github.com/pulumi/pulumi-command/tree/fa03b2e50bee15d6824bc9e43d94d08d01fcf2c9#graceful-cleanup-of-workloads-in-a-kubernetes-cluster) shows a different `kubectl` command, but you can swap that out.

We're still experimenting in this area, so please keep the feedback coming!

**Comment by jordiprats** [comment]
@lblackstone an actual shell command feels quite dirty. I feel it's not the best approach

**Comment by rodrigobrim** [comment]
Why are we still discussing this need after 5 years? There are a lot of examples, but we don't need examples. We need the already existent feature called patch.

What's the problem to implement it?

**Comment by lblackstone** [comment]
Thanks for your continued patience as we work through this. While the problem may appear to be simple, it has turned out to be subtle and complex to solve for the general case. (Terraform seems to be [having similar struggles](https://github.com/hashicorp/terraform-provider-kubernetes/issues/723)). This issue continues to be a regular source of discussion at Pulumi, and we’re making progress towards fixing it. We’re eager to get this resolved, and will make an effort to update this issue more regularly until it is.

## Current workaround

As I mentioned in a [previous comment](https://github.com/pulumi/pulumi-kubernetes/issues/264#issuecomment-1004946651), you can work around this today using the `pulumi/command` provider. This obviously isn’t an ideal solution, but serves as a general purpose “escape hatch” for cases where we don’t yet have integrated support for a feature from another tool.

```typescript
import { local } from "@pulumi/command";

// We could also use `RemoteCommand` to run this from within a node in the cluster
new local.Command(“patch”, {
    create: "kubectl patch serviceaccount default -p '{"imagePullSecrets": [{"name": "registry-<my-registry>"}]}'",
    environment: {
        KUBECONFIG: <kubeconfig>,
    },
});
```

## Progress update

The main reason why this issue has been so tricky is that it’s adapting an imperative workflow (patch a resource) to integrate with Pulumi’s declarative resource model. This is unlike `kubectl`, which provides both imperative (e.g., patch, scale) and declarative (e.g., create, apply) commands.

There are several unresolved issues currently blocking the design I proposed in this [previous comment](https://github.com/pulumi/pulumi-kubernetes/issues/264#issuecomment-560933184):

### Lack of patch primitive

Pulumi doesn’t currently support a discrete “patch” operation on unmanaged (i.e., not tracked in Pulumi state) resources. While it does support a Read operation that can query an arbitrary resource’s current state, it’s not possible to subsequently modify this state without first [importing](https://www.pulumi.com/docs/guides/adopting/import/) the resource. 

In most of the use cases mentioned in this issue thread, the users don’t want Pulumi to assume full management of the resource. This makes import a bad option because it requires several discrete steps to import, update, and then “unimport” the resource. This is achievable programmatically with the [Automation API](https://www.pulumi.com/docs/guides/automation-api/), but requires more work. We are still considering what it would look like to support a general purpose patch operation in Pulumi.

### Await/readiness logic

A major problem with mixing imperative steps into a declarative workflow is knowing when to run the operations, and when the operation is done. We have adapted the Kubernetes eventual consistency model to work with Pulumi by using [await logic](https://www.pulumi.com/blog/improving-kubernetes-management-with-pulumis-await-logic/) to determine when resources are ready.

Patching a resource requires that the resource exists, and it’s not easy to determine that reliably. Pulumi’s Read operation fails if the resource doesn’t exist, and there’s no built-in way to retry on failure with a timeout in case the resource failed to appear for some reason. We’re tracking improvements to the [get resource workflow](https://github.com/pulumi/pulumi-kubernetes/issues/1656), which would address this part of the problem. 

We also recently started splitting out the await logic from the provider into [a separate library](https://github.com/pulumi/cloud-ready-checks), which will enable us to check resource readiness apart from the core resource update lifecycle. The combination of a retry-able Read operation and await logic will enable us to run a patch operation in the correct order during an update.

### Server-side apply support

Since patching implies that we are sharing management of a resource, we will likely want to implement the patch feature using [server-side apply (SSA)](https://kubernetes.io/docs/reference/using-api/server-side-apply).  Using SSA allows us to specify the particular field that is being patched by Pulumi rather than potentially conflicting with other resource managers. In the case of a conflict, the cause will be much more apparent and easier to resolve. Today, our Kubernetes provider uses client-side apply for all resource operations, so [additional work](https://github.com/pulumi/pulumi-kubernetes/issues/1879) will be required to use SSA.

**Comment by jordiprats** [comment]
I think this should be implemented just as the exec resource is implemented in puppet, ie:

```
    exec { 'set timezone - timedatectl':
      command => "timedatectl set-timezone ${timezone::timezonename}",
      unless  => "timedatectl status | grep \"Time zone: ${timezone::timezonename}\"",
      path    => '/usr/sbin:/usr/bin:/sbin:/bin',
    }
```

So, you should be able to define how to retrieve the value and then how to patch it, just what it's doing this script without having to import the resource. I mean, having a patch is all about not having the resource on the state, isn't it?

```
OUTPUT=$(kubectl get daemonset aws-node -n kube-system \
    -o jsonpath='{.spec.template.spec.initContainers[?(@.name == "aws-vpc-cni-init")].env[?(@.name == "DISABLE_TCP_EARLY_DEMUX")].value}'
)

if [ "$OUTPUT" != "true" ]; then
    kubectl patch daemonset aws-node -n kube-system -p '{
        "spec": { "template": { "spec": { "initContainers": [ {
            "env": [
                {
                    "name" : "DISABLE_TCP_EARLY_DEMUX",
                    "value" : "true"
                }
            ],
            "name" : "aws-vpc-cni-init"
        } ] } } }
    }'
fi
```

Just my two cents

**Comment by alex-hunt-materialize** [comment]
Perhaps most of this could be provided by simply allowing import of existing resources without matching values. In that case, the system should first import it and then apply changes to reconcile the differences. This might not be possible for all providers, but should be trivial for Kubernetes resources.

**Comment by lblackstone** [comment]
I'm excited to announce that we've identified a design that should finally resolve this issue! You can read the [detailed proposal](https://github.com/pulumi/pulumi-kubernetes/issues/2011) and respond with any comments or questions on that issue.

We plan to start work on the implementation next week. Thanks again to everyone who has provided feedback, and for your continued patience as we work through this complex issue!

**Comment by lblackstone** [comment]
With the [v3.20.1 release](https://github.com/pulumi/pulumi-kubernetes/releases/tag/v3.20.1) out now, I'm going to mark this as complete! 🎉 

Check out the [how-to guide](https://www.pulumi.com/registry/packages/kubernetes/how-to-guides/managing-resources-with-server-side-apply/) for some examples to get started. Note that this feature is currently opt-in with a provider flag, but is expected to become the new default in the future.

Please open new issues if you run into any problems, and thanks again for everyone's input on this feature!

**Comment by luillyfe** [comment]
Still is not clear enough to me how to use this feature to replace:
```yaml
kubectl annotate serviceaccounts serviceAccountName -n clusterNamespace \
    iam.gke.io/gcp-service-account=fully-quallified-service-account-name
```

**Comment by lblackstone** [comment]
@luillyfe You can use a [patch resource](https://www.pulumi.com/registry/packages/kubernetes/how-to-guides/managing-resources-with-server-side-apply/#patch-a-resource) for this. Please open a new issue if you're running into problems with this feature.
