### ISSUE TITLE
ReplicaSet await logic hanging if resource modified by another controller

### ISSUE THREAD

**Issue by lblackstone** [pulumi/pulumi-kubernetes#2662]
It looks like there's a bug in the await logic for ReplicaSets where changes made to the resource by another controller are not detected. As a result, the resource hangs indefinitely waiting for readiness.

              hey @lblackstone @jsravn, I'm running into this very reliably and I think your assessment 
> after a lot of debugging we found this happens if something in the cluster is modifying the pod spec after deployment 

Is likely accurate. I'm on GCP GKE using Autopilot mode, and I'm running into this only when I modify my deployment's podspec resource limits. I can modify resource requests no problem, but resource limits reliably causes the operation to hang. I presume this has something to do with [autopilot magic around resource limits](https://cloud.google.com/kubernetes-engine/docs/concepts/autopilot-resource-requests#min-max-requests) causing the podspec modification you mentioned

_Originally posted by @jtmarmon in https://github.com/pulumi/pulumi-kubernetes/issues/1978#issuecomment-1806194070_

**Comment by nwittstruck** [comment]
Just as an additional data point: I'm experiencing the same issue when editing the podspec on a non-GKE cluster. For me, it wasn't the resource limits that caused this, but changing the image pull policy.

**Comment by ringods** [comment]
The `other controller` aspect is not so much the issue. As mentioned by @nwittstruck, it is when something in the pod spec is changed which does **not** lead to a new `ReplicaSet` created by the Kubernetes engine. Our provider is a bit too eager in expecting a new `ReplicaSet` and waits for it.

I could reproduce this quite easily on my local Kubernetes cluster from Docker Desktop with the following steps:

* deploy the following yaml file, using `kubectl apply -f deployment-nginx.yaml`

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.14.2
          ports:
            - containerPort: 80
```

* create a new Pulumi Kubernetes project: `pulumi new kubernetes-typescript`
* import the `Deployment` into the stack: `pulumi import "kubernetes:apps/v1:Deployment" nginx-deployment "default/nginx-deployment"`
* replace the `deployment` from the Pulumi template with the generated code you get from the import command. It should look like this:

```ts
import * as pulumi from "@pulumi/pulumi";
import * as kubernetes from "@pulumi/kubernetes";

const nginx_deployment = new kubernetes.apps.v1.Deployment("nginx-deployment",
    {
        apiVersion: "apps/v1",
        kind: "Deployment",
        metadata: {
            annotations: {},
            labels: {
                app: "nginx",
            },
            name: "nginx-deployment",
            namespace: "default",
        },
        spec: {
            progressDeadlineSeconds: 600,
            replicas: 3,
            revisionHistoryLimit: 10,
            selector: {
                matchLabels: {
                    app: "nginx",
                },
            },
            strategy: {
                rollingUpdate: {
                    maxSurge: "25%",
                    maxUnavailable: "25%",
                },
                type: "RollingUpdate",
            },
            template: {
                metadata: {
                    labels: {
                        app: "nginx",
                    },
                },
                spec: {
                    containers: [{
                        image: "nginx:1.14.2",
                        imagePullPolicy: "IfNotPresent",
                        name: "nginx",
                        ports: [{
                            containerPort: 80,
                            protocol: "TCP",
                        }],
                        resources: {},
                        terminationMessagePath: "/dev/termination-log",
                        terminationMessagePolicy: "File",
                    }],
                    dnsPolicy: "ClusterFirst",
                    restartPolicy: "Always",
                    schedulerName: "default-scheduler",
                    securityContext: {},
                    terminationGracePeriodSeconds: 30,
                },
            },
        },
    },
    {
        protect: true,
    }
);
```

* Run `pulumi up` and verify that there are no changes.
* Remove line `schedulerName: "default-scheduler",` since this is the default value for `schedulerName`.
* Run `pulumi up` again. Kubernetes will **not** create a new `ReplicaSet` but our provider will wait for one.

<img width="1106" alt="Screenshot 2024-01-11 at 14 05 34" src="https://github.com/pulumi/pulumi-kubernetes/assets/77923/a62f11e0-bc06-42c4-9124-89da4ab2023a">

The `pulumi up` execution will time out after 10 minutes. The only way to get past this is to use the `pulumi.com/skipAwait` annotation. This is not so much a problem for this small example, but it is a problem for the customer that reported a problem matching this issue.
