### ISSUE TITLE
When a Secret contains a `\n` at the end it constantly tries to replace it

### ISSUE THREAD

**Issue by rshade** [pulumi/pulumi-kubernetes#2681]
### What happened?

We have a couple of secrets that have new lines at the end of them. Pulumi updates the secret, then on the next up, tries to replace it. This didn't happen in the version 3 provider. 

### Example

```
import pulumi
from pulumi_kubernetes.core.v1 import Secret
from pulumi_kubernetes.meta.v1 import ObjectMetaArgs

var_secret: str = "test\n"


new_secret: Secret = Secret(
    resource_name="test-secret",
    metadata=ObjectMetaArgs(
        name="test-secret",
        namespace="kube-system"
    ),
    data={
        "pvt.key": var_secret,
    },
    type="Opaque"
)
```

### Output of `pulumi about`

```
CLI
Version      3.94.2
Go Version   go1.21.4
Go Compiler  gc

Plugins
NAME        VERSION
kubernetes  4.5.5
python      unknown

Host
OS       ubuntu
Version  20.04
Arch     x86_64

This project is written in python: executable='/usr/bin/python3' version='3.8.10'

Current Stack: richard-shade-pulumi/pulumi-kube-secret/dev

TYPE                         URN
pulumi:pulumi:Stack          urn:pulumi:dev::pulumi-kube-secret::pulumi:pulumi:Stack::pulumi-kube-secret-dev
pulumi:providers:kubernetes  urn:pulumi:dev::pulumi-kube-secret::pulumi:providers:kubernetes::default_4_5_5
kubernetes:core/v1:Secret    urn:pulumi:dev::pulumi-kube-secret::kubernetes:core/v1:Secret::test-secret




Dependencies:
NAME               VERSION
pip                23.3.1
pkg_resources      0.0.0
pulumi-kubernetes  4.5.5
setuptools         69.0.2
wheel              0.42.0

Pulumi locates its logs in /tmp by default
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by rquitales** [comment]
This is probably related to how we convert `stringData` to `data` in input diff, compared to what Kubernetes does.
Related to #2511.

**Comment by rquitales** [comment]
Upon revisiting the initial bug report, it seems that the issue lies in attempting to use the `data` field instead of `stringData` as I previously thought. According to the Kubernetes documentation (ref: https://kubernetes.io/docs/concepts/configuration/secret/#restriction-names-data), the `data` field requires all values for keys to be base64-encoded strings. Therefore, the correct approach for storing the value "test\n" within the `data` field is as follows:

```python
import base64

var_secret: str = "test\n"
var_encoded = base64.b64encode(var_secret.encode("utf-8")).decode("utf-8")

new_secret: Secret = Secret(
    resource_name="test-secret",
    metadata=ObjectMetaArgs(
        name="test-secret",
        namespace="kube-system"
    ),
    data={
        "pvt.key": var_encoded,
    },
    type="Opaque"
)
```

It's crucial to note that if the value provided is not base64-encoded, the Kubernetes API server will trigger a validation error during the secret creation process. The specific string provided, "test\n", happens to be base64-decodable by the K8s API server for validation. Failure to adhere to this encoding requirement results in a validation error, as demonstrated in the following failure scenario where a non-encoded value like `var_secret: str = "test string\n"` leads to:

```
Diagnostics:
  kubernetes:core/v1:Secret (test-secret):
    error: resource default/test-secret was not successfully created by the Kubernetes API server : failed to convert new object (default/test-secret; /v1, Kind=Secret) to proper version: unable to convert unstructured object to /v1, Kind=Secret: error decoding from json: illegal base64 data at input byte 4
```

---

Alternatively, users who prefer not to handle base64 encoding manually can use the `stringData` field. This allows the Kubernetes API server to perform the base64 encoding. For example:

```python
import pulumi
from pulumi_kubernetes.core.v1 import Secret
from pulumi_kubernetes.meta.v1 import ObjectMetaArgs

var_secret: str = "test\n"

new_secret: Secret = Secret(
    resource_name="test-secret",
    metadata=ObjectMetaArgs(
        name="test-secret",
        namespace="kube-system"
    ),
    string_data={                     # <- This is the difference.
        "pvt.key": var_secret,
    },
    type="Opaque"
)
```

It's worth noting that using `stringData` does not trigger a spurious diff when the secret ends with a `\n`.

Considering this clarification and the nature of the issue, I will be closing this bug report. If you have any further questions or concerns, feel free to reopen the issue or create a new one.

**Comment by rshade** [comment]
This affects it also if the base64 data has a `\n` as well which is the case for the client. In <4.x provider versions it was able to tell they were the same and did not re-apply each time. We should either early warn on this(best case) or strip it before we compare.

**Comment by rquitales** [comment]
Thanks for the clarification. Note, this issue does not exist if they use base64 libraries to do the encoding programatically, for example, the following pulumi program does not repro:

```
var_secret: str = "dGhpcyBpcyBhIHRlc3Qgc3RyaW5n"
encoded_string = base64.b64encode(var_secret.encode("utf-8")).decode("utf-8")
encoded_string += "\n"

print(f"'{encoded_string}'") # <- Printing to ensure a new line is included.

new_secret: Secret = Secret(
    resource_name="test-secret",
    metadata=ObjectMetaArgs(
        name="test-secret",
        namespace="default"
    ),
    string_data={
        "pvt.key": var_secret,
    },
    type="Opaque"
)
```

But this repros the issue:

```
var_secret: str = "dGhpcyBpcyBhIHRlc3Qgc3RyaW5n\n" #<- This is the base64 encoding of `this is a test string`


new_secret: Secret = Secret(
    resource_name="test-secret",
    metadata=ObjectMetaArgs(
        name="test-secret",
        namespace="kube-system"
    ),
    data={
        "pvt.key": var_secret,
    },
    type="Opaque"
)
```

Will continue looking into tis.
