### ISSUE TITLE
v3.helm.Release error: cannot re-use a name that is still in use

### ISSUE THREAD

**Issue by awopenphone** [pulumi/pulumi-kubernetes#2758]
### What happened?

Most of my chart installs that are already installed in the cluster fail to install with a conflicting name.

### Example

```+   ├─ kubernetes:helm.sh/v3:Release  name                        **creating failed**     1 error
  kubernetes:helm.sh/v3:Release (name):
    error: cannot re-use a name that is still in use
      warning: Helm release "snip" was created but has a failed status. Use the `helm` command to investigate the error, correct it, then retry. Reason: context canceled
    error: 1 error occurred:
    	* Helm release "snip/snip" was created, but failed to initialize completely. 
```

### Output of `pulumi about`

CLI          
Version      3.101.1
Go Version   go1.21.6
Go Compiler  gc

Plugins
NAME        VERSION
aws         6.18.0
awsx        2.4.0
docker      4.5.0
docker      3.6.1
kubernetes  4.7.0
nodejs      unknown

Host     
OS       darwin
Version  14.2.1
Arch     arm64

This project is written in nodejs: executable='/Users/andrew/.nvm/versions/node/v18.18.2/bin/node' version='v18.18.2'

Current Stack: snips

TYPE                           URN
snip
kubernetes:helm.sh/v3:Release  urn:pulumi:snip::infra::kubernetes:helm.sh/v3:Release::snip

Found no pending operations associated with snip

Backend        
Name           pulumi.com
snip
Token type     personal

Dependencies:
NAME                VERSION
jest                29.7.0
@pulumi/aws         6.18.0
@pulumi/kubernetes  4.7.0
@swc/jest           0.2.30
@types/jest         29.5.11
@types/js-yaml      4.0.9
@pulumi/awsx        2.4.0
@pulumi/pulumi      3.101.1
@types/node         20.11.5
js-yaml             4.1.0

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by mjeffryes** [comment]
some discussion on community slack: https://pulumi-community.slack.com/archives/CRFURDVQB/p1705593191676569

**Comment by rquitales** [comment]
Summarizing some notes from the issue author in the Slack conversation for easier reference.

1. The issue seems to occur when the user re-runs `pulumi up` on a Helm release resource in which they previously used pulumi to destroy
2. It might be likely that there is an error cleaning up the helm deployment, where the chart is in a pending state so cleanup isn't possible
3. Re-running `pulumi up` in the past used to do a `helm upgrade`, whereas current versions of the kubernetes provider (v4.7.0) is attempting to do `helm install` which results in the name conflict.
4. The author noted that v4.5.0 of the provider used to run a helm upgrade instead of a helm install, so this change in behaviour likely occurred between v4.5.0 and v4.7.0.

I've attempted to try and reproduce this issue in the 2 specified kubernetes provider version but was unable to. It's likely that my attempts at trying to deploy a problematic helm Release may be insufficient to hit the error encountered by users.

https://github.com/martinjt/aks-otel-demo/blob/main/infra/Applications/OtelDemo.cs is another complete helm example provided by @martinjt in the Slack conversation which may be useful in attempting to replicate this error.

**Comment by awopenphone** [comment]
Okay I realize that my issue was ignorance of the change in @pulumi/kubernetes 4.7.0 that replaced helm upgrade with helm install. While this impacted my pulumi stacks, it is not a bug as originally reported. It would be nice if there was an option to use upgrade since as far as I can tell this now requires two pulumi runs to change a helm release (one destroy, one up). It also reduces the viability of stacks with multiple helm charts since adding and removing one or more per time is now a more manual process and or involves CD of a full delete of the changed resource which is considerable more overhead to implement in Github Actions.

**Comment by troinine** [comment]
> I've attempted to try and reproduce this issue in the 2 specified kubernetes provider version but was unable to. It's likely that my attempts at trying to deploy a problematic helm Release may be insufficient to hit the error encountered by users.

You should be able to reproduce this with a secret that is marked to be kept when a release is uninstalled:

```
apiVersion: v1
kind: Secret
metadata:
  annotations:
    "helm.sh/resource-policy": "keep"
```

I would guess any manifest that is marked with policy `keep` would reproduce the issue.  The process for us to reproduce this is as follows:

1. Run `pulumi up`
2. Run `pulumi destroy` and observe the warning about resource that are annotated with the given resource policy
3. Run `pulumi up`

You can then see the following error:

```
Diagnostics:
  kubernetes:helm.sh/v3:Release (redacted):
    error: rendered manifests contain a resource that already exists. Unable to continue with install: Secret "redacted-secrets" in namespace "redacted" exists and cannot be imported into the current release: invalid ownership metadata; annotation validation error: key "meta.helm.sh/release-name" must equal "redacted-ef76f584": current value is "redacted-cf480c8c"
```

As mentioned in earlier comments, this used to work with previous versions and it was useful because we have a use case where we don't want to regenerate some secrets between install / uninstall cycles as those are stored in persistent volumes.
