### ISSUE TITLE
Decision on whether to create a component resource for kubernetes:helm.sh:v3/Chart or deprecate

### ISSUE THREAD

**Issue by mjeffryes** [pulumi/pulumi-kubernetes#2788]
A significant number of open bugs in the project are related to the `Chart` resource specifically.

https://github.com/pulumi/pulumi-kubernetes/issues?q=is%3Aopen+is%3Aissue+label%3Akind%2Fbug+label%3Aarea%2Fhelm+label%3Amro2
https://github.com/pulumi/pulumi-kubernetes/issues?q=is%3Aopen+is%3Aissue+label%3Akind%2Fbug+label%3Aarea%2Fhelm+label%3Amro1

In principle, the `Chart` resource could be deprecated and users encouraged to either 
1) use the `Release` resource if they want to match helm exactly, or
2) use `helm template` + the `ConfigGroup` resource to convert the helm chart to kubernetes resources (with some loss in fidelity around lifecycle). 

We suspect that deprecating may be the best course here because it makes the choice more explicit to users.

**Comment by EronWright** [comment]
I would advocate for a new `Chart` resource ("v4") with the semantics of [`helm template`](https://helm.sh/docs/helm/helm_template/) and written as an [MLC](https://www.pulumi.com/blog/pulumiup-pulumi-packages-multi-language-components/).

**Comment by jwilliams-fn** [comment]
[This page](https://www.pulumi.com/registry/packages/kubernetes/how-to-guides/choosing-the-right-helm-resource-for-your-use-case) highlights the tradeoffs between `Release` and `Chart`:
- Release:
   - Fire & Forget deployments
   - Interoperability with `helm`
- Chart:
  - Python transformations
  - Rich previews/diffs
  - CrossGuard policy enforcement

Why we use `Chart` over `Release`:

1. We explicitly will *never* have "Fire & Forget" deployments (see # 2)
2. Our company uses of transformations with ALL helm releases which are *significantly* easier with `Chart`
3. Rich previews/diffs (`Release` is a [black box](https://en.wikipedia.org/wiki/Black_box#:~:text=In%20computing%20in%20general,%20inner%20workings), while `Chart` is open/understandable)

> The biggest reason our organization uses Chart is the ability to apply transformations on the rendered chart. We do things like add our own sidecars and labels on resources to match our platform's requirements, and transform some standard fields, like images get redirected to internal mirrors.

Just adding onto this, we are aware it is possible to apply transformations with `Release` by using an external executable, like `kustomize`, but the ability to do transformations with python code inline with the pulumi resource declaration is much easier and far more understandable than having a separate config/script to apply the transformations.

We originally used `Release` + `kustomize`, but quickly switched to `Chart` + python for the same transformations because they were far easier to implement and maintain.

Also, being able to see what resources will be created/modified/deleted is very useful and important to us. That is just not possible with `Release` today and `Chart` gives us the visibility we need for all our cloud resources.

**Comment by EronWright** [comment]
We took the decision to continue to support and invest in the `Chart` resource.  See [decision log](https://docs.google.com/document/d/1_Mci7hmDY4Rhr2UEjZQ4IEpr1D8FdH8kYVk_ZGJC6bc/edit#heading=h.q8fuoftnfr6b).
