### ISSUE TITLE
Auto-generate container names

### ISSUE THREAD

**Issue by lblackstone** [pulumi/pulumi-kubernetes#301]
It seems like we could also auto-generate the name field in the `core.v1.Container` type, similar to #103

**Comment by hausdorff** [comment]
I think it's likely we do not want to do this automatically. I don't see many cases where you'd want this, and also, munging a deep part of such important resource types would be highly unintuitive to users, it runs a very high risk of having strange failure modes since `name` is used as the merge key in the `apply` logic, and _lots_ of things expect that these names are stable and not changed out-of-band by the client.

Should we close this?
