### ISSUE TITLE
User agent header not correct

### ISSUE THREAD

**Issue by ringods** [pulumi/pulumi-kubernetes#3267]
### What happened?

A customer reports that the HTTP header used for the user agent is not sent correctly. See the example below.

* the header name should not be `userAgent` but `User-Agent`
* the actual provider binary version is missing. It reports `v0.0.0`
* there is a possible interpolation not working correctly, leading to an explicit `$Format` string being rendered

### Example

Taken from the Kubernetes audit logs:

```
"userAgent": "pulumi-resource-kubernetes/v0.0.0 (darwin/arm64) kubernetes/$Format",
```

### Output of `pulumi about`

```
CLI
Version      3.134.1
Go Version   go1.23.1
Go Compiler  gc

Plugins
KIND      NAME        VERSION
resource  aws         6.53.0
resource  cloudinit   1.4.7
resource  kubernetes  4.18.1
language  python      unknown
resource  random      4.16.5

Host
OS       darwin
Version  14.5
Arch     arm64
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by blampe** [comment]
@ringods can you share how the user is setting this header? Is this part of an Automation API program?

**Comment by rquitales** [comment]
The user-agent is likely coming from client-go's default:
https://github.com/kubernetes/client-go/blob/23900f492969db045e8a36396852381fd189569b/rest/config.go#L495-L508

Without digging too deep, the fix for this probably requires us to accurately set the user-agent here:
https://github.com/pulumi/pulumi-kubernetes/blob/605307c42f5c0044227064c357afe4ec852735e3/provider/pkg/provider/provider.go#L828-L859
