### ISSUE TITLE
CI tests are not guaranteed to clean up created resources

### ISSUE THREAD

**Issue by lblackstone** [pulumi/pulumi-kubernetes#365]
Bugs in the provider code can currently orphan k8s resources on the CI cluster, and then cause failures on subsequent CI runs. We should make sure that test resources are cleaned up at the end of the run, even if the provider did not clean them up properly.

**Comment by hausdorff** [comment]
Talking a bit offline with @lblackstone, I think the exit criteria here are:

- [ ] Integration tests should continue to run in a CI cluster so that we continue to expose issues like failure to clean up resources
- [ ] Integration tests should fail if, after the run finishes, there are leftover resources.

This probably won't fit into M21 because k8s has weird background delete semantics. Might be worth doing in M22, but realistically I'm guessing that we won't get to this until it bites us again. :)
