### ISSUE TITLE
API docs issues

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi-kubernetes#373]
There is no `helm` module at https://pulumi.io/reference/pkg/nodejs/@pulumi/kubernetes/index.html, seems we show `v2` there (which should be a submodule of `helm`)?

There are no/few docs on https://pulumi.io/reference/pkg/nodejs/@pulumi/kubernetes/v2/, apparently because we use `//` comments instead of `/** **/` JS doc comments.

**Comment by lukehoban** [comment]
I think the problem is actually all the uses of `//`. Those docs aren’t picket up by the doc generator. 

Re: the overloads - I’m not sure whether that prevents generating useful IDE and/ doc content - but if it does I’d argue we should generate as many comments as needed.

**Comment by lblackstone** [comment]
Helm is showing up as `v2` in the API docs because the resources live in the `v2` namespace, which is then imported under the `helm` namespace in the kubernetes-provider: https://github.com/pulumi/pulumi-kubernetes/blob/08eb3b9307fb63fcf32d275e61653271bbbc498e/sdk/nodejs/index.ts#L2-L3

I think the preferred solution would be to move Helm resources to a separate package (https://github.com/pulumi/pulumi-kubernetes/issues/175), but we could possibly also update `tsdocgen` to handle this special case.

**Comment by lblackstone** [comment]
I've poked at this for a bit, and decided I need to work on some basic cleanup before I can address the doc issues. The root cause of the k8s API doc problems seem to be related to the `tsdocgen` tool, and the fact that the k8s provider is laid out very differently than the terraform-generated providers. 

I'm going to tackle #479 as a starting point, and try to make the layout match what `tsdocgen` is expecting.

Given the extra scope of the work, this won't make it in for M21, but should land early in M22.
