### ISSUE TITLE
Docs are missing all resources

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi-kubernetes#393]
None of the actual resource classes are included in the API docs at, e.g. https://pulumi.io/reference/pkg/nodejs/@pulumi/kubernetes/apps/v1/.

Since the dominant thing that users use are `new Resource`, this appears to mean that almost none of what users interact with is included in the documentation.

Further, what is included are raw interfaces without `Input`/`Output` included - which are not what is interacted with in normal cases.  This part is likely related to https://github.com/pulumi/pulumi-kubernetes/issues/336, but leads to very misleading documentation of even that parts that are included.

**Comment by lblackstone** [comment]
From what I can see, these docs are being generated and included in the TS package, but the `tscdocgen` tool is expecting them to be in the same layout as the tf-generated packages.
https://github.com/pulumi/pulumi-kubernetes/blob/08eb3b9307fb63fcf32d275e61653271bbbc498e/sdk/nodejs/provider.ts#L4058-L4140

@hausdorff Would it break anything horribly to generate the types in the expected format? Specifically, it appears that the other providers split definitions into separate folders/files by type rather than including them all in a top-level `provider.ts` file with namespaces.

**Comment by lukehoban** [comment]
Note that the problem here may well be in our `tsdocgen` utility in the docs repo.  Or in some interaction between the API style here and that understood by that tool.  If there’s a simple fix on the docgen side without requiring changes here we should look into that as wel.

**Comment by joeduffy** [comment]
> Note that the problem here may well be in our tsdocgen utility in the docs repo. 

I'm fairly certain that's the problem. `tsdocgen` is highly customized to make our packages look good in the emitted docs. This was the way we eliminated the problems with our prior TypeScript docs solution (I forget its name), which emitted tons of modules; we instead flatten them.

For example, `aws/s3` is a module that exports all `Bucket`, etc related types. In reality, it should also show that it emits `aws/s3/bucket`, etc modules, but we filter that out. This is probably why Kubernetes sub-modules aren't getting picked up.

I do think there's also some oddities in the way we export Kubernetes `types/input`, etc., which I've never been a huge fan of (it makes getting at some common interfaces awkward). This may be contributing to the problem also, since I assume we want all those interfaces in the docs too.

**Comment by lblackstone** [comment]
Related to #373 

This will also be addressed early in M22
