### ISSUE TITLE
Any way to skip duplicate objects?

### ISSUE THREAD

**Issue by kameshsampath** [pulumi/pulumi-kubernetes#510]
/question

Am currently trying to install istio + knative with pulumi, when i do `pulumi up` I get the following error:

```
  kubernetes:apiextensions.k8s.io:CustomResourceDefinition (images.caching.internal.knative.dev):
    error: Duplicate resource URN 'urn:pulumi:development::knative-installer::kubernetes:yaml:ConfigGroup$kubernetes:yaml:ConfigFile$kubernetes:apiextensions.k8s.io/v1beta1:CustomResourceDefinition::images.caching.internal.knative.dev'; try giving it a unique name
```
Is there anyway i can tell pulumi to skip duplicate object creation ? As these components can be installed separately they tend to have few redundant objects in their dpeloyment yamls.

**Comment by hausdorff** [comment]
Recapping the conversation from Slack: I think we’d have to have a _very_ good reason to allow “skipping” resources that exist. It’s contrary to our model is so many ways, it’s hard even to see how it might work.

For example: when a chart or application asks you to create a specific version of a resource, and your resource version differ, what should we do? What happens if someone deletes that CRD out from under you? What happens if they delete it and you run `pulumi up`? And so on.

Besides all that, when this _does_ happen it’s virtually certain to be a bug in the chart or app. I very seriously doubt that what you _really_ want is for pulumi to choose arbitrarily between the two versions of a resource when there’s a conflict. :)

**Comment by hausdorff** [comment]
I normally would not do this so quickly, but I'm going to proactively mark this `wont-fix` and close the issue, because I think the likelihood that we will be able to justify to the rest of the Pulumi core that this is the way to go is very, very small. :)

If you would like to present more evidence this is something we should consider, please do feel free to -- always a chance I'm missing something.
