### ISSUE TITLE
`refresh` and `up` after manual delete of CRDs fail

### ISSUE THREAD

**Issue by hausdorff** [pulumi/pulumi-kubernetes#526]
When a user deletes CRDs out-of-band, it will destroy the underlying CRs, too. When we do a `refresh` or an `up` subsequently, it will then present an error saying that it can't find that resource type registered.

This is probably not what users expect. It seems like a better experience is to interpret the "missing type" error as a deletion of the CRD and the underlying CRs.

**Comment by lblackstone** [comment]
After further investigation, the root cause here is the dynamic client erroring out on the REST mapping for the specified Kind. Since this is part of the client init, it can occur on any CRUD operation if the CRD is not registered.

The provider includes retry logic on Create, which generally handles the case where the CRD is being registered by another resource. Read, Update and Delete do not currently include retry logic.

There are a couple thorny issues here:
1. We don't don't track an explicit dependency between CRDs and any related CRs.
1. Some Helm charts create CRDs "out of band", using operators, Jobs, or separate charts.

Given these complexities, I'm not sure how to distinguish between the case where 
1. A CRD is not registered yet, but is expected to be,
1. A CRD was deleted or not created, and any operation involving a related CR will not succeed.

**Comment by hausdorff** [comment]
For `refresh`, if we attempt to read the live state of a CR and the API server tells us that it can't find the relevant type/CRD, I think it's fine to consider the resource deleted -- if a CR's CRD is not registered, it cannot possibly exist in that cluster.

For `up`, if a CRD is deleted out-of-band we won't notice until we run a `refresh` or change the CRD/CRs, and so I think it's actually fine to just make sure `refresh` copes with the problem. If we run `up` after changing the CR, the error will tell the truth, which is that the CRD doesn't exist, and I think that's fine.

For `delete`, if a CRD is deleted out-of-band and we attempt to delete a CR, I think the "missing CRD" error should just be interpreted as having already been deleted.

**Comment by joeduffy** [comment]
Overall, agree with @hausdorff's conclusion. One question:

> if a CR's CRD is not registered, it cannot possibly exist in that cluster.

If that is true, I tend to agree. However, would this not just fall out as part of `refresh`'s behavior, since we would then check whether the CDs existed, and be told "no"? I'm just trying to understand whether/why this needs to be a special case, rather than just a transitive property of `refresh`.

**Comment by joeduffy** [comment]
As an aside, @lblackstone's comment:

> We don't don't track an explicit dependency between CRDs and any related CRs.

Has caused several of us, and our customers, a bit of pain. Is this tracked elsewhere?

**Comment by hausdorff** [comment]
> However, would this not just fall out as part of refresh's behavior, since we would then check whether the CDs existed, and be told "no"?

I'm not quite sure what you mean, but to be 100% clear: (1) we're proposing `refresh` does succeed even if a resource is in an unhealthy state, (2) `up` will thus require _no changes_, as its semantics "fall out of" `refresh`. Hopefully that clears things up.

**Comment by joeduffy** [comment]
I see, I guess your comment here is the key:

> and the API server tells us that it can't find the relevant type/CRD

Upon reading, the API server will return a particular error saying "CRD of type z cannot be found", which -- although it's not saying "CR named x of type z cannot be found," we can assume that the absence of CRD of type z implies the absence of any individual CR named x. Makes sense.

**Comment by lblackstone** [comment]
> As an aside, @lblackstone's comment:
> 
> > We don't don't track an explicit dependency between CRDs and any related CRs.
> 
> Has caused several of us, and our customers, a bit of pain. Is this tracked elsewhere?

@joeduffy No, I don't think this is tracked yet. This is a special case, and in general, k8s will converge to a working state when all the relevant resources are submitted.

We're going to need to improve handling of this failure condition, but I'm not sure if explicit dependencies are the answer for k8s resources.

**Comment by joeduffy** [comment]
> We're going to need to improve handling of this failure condition, but I'm not sure if explicit dependencies are the answer for k8s resources.

This is how I've seen users working around the problem. Is there a more appropriate solution for them? Increased timeouts?

**Comment by lblackstone** [comment]
@joeduffy Sorry, let me clarify:

For Create, the provider already retries, and this covers the majority of cases we've seen. I fixed Read/Update/Delete in the linked PR so that these operations don't fail for a missing CRD.

The dependency problem really only applies to resources created from YAML/Helm since we don't infer `dependsOn` info for the underlying resources. Dependencies work as expected if the resources are created natively in Pulumi.

**Comment by hausdorff** [comment]
I've started to capture the dependency information with an issue that focuses on the _consequences_ of not tracking this dependency information: https://github.com/pulumi/pulumi-kubernetes/issues/531

I believe this actually captures the "essence" of most of this pain -- would be nice ot collect the discussion over there.
