### ISSUE TITLE
Resource namespace should take precedence over Provider Namespace

### ISSUE THREAD

**Issue by geekflyer** [pulumi/pulumi-kubernetes#576]
This is a follow up to https://pulumi-community.slack.com/archives/C84L4E3N1/p1559169211137000

Due to some recent change (I personally observed this @pulumi/kubernetes: 0.23.1 onwards but it may have been introduced earlier) pulumi now respects the `namespace` property if set on the provider level.
If both on the provider and the k8s resource an explicit namespace is set, the provider namespace takes precedence.

As mentioned by @lblackstone this behavior is currently intended.

After giving it some thought I concluded that I personally find this behavior unintuitive and think **swapping the precedence (i.e. resource namespace takes precedence over provider namespace) would be the better design**.

In general most tools / designs / apis have the behavior that an attribute set on a more "narrow" / specific level (i.e. Resource) takes precedence over the attribute set on the broader / wider level (i.e. Provider) and I don't see a good reason why pulumi k8s should deviate from this convention and surprise users.

If you had a specific use case in mind when the current design was chosen I'm happy to hear about it :)

Here my original slack message:

> Did something recently changed with regards to precedence rules of provider attributes in the kubernetes (typescript) provider? I recently upgraded to `@pulumi/kubernetes: 0.23.1` and seeing some odd behaviour: We instantiate provider instances dynamically via `new gcp.Provider({kubeconfig: ..., namespace: 'namespace-A'})` and then use this provider instance in some resources like `new k8s.core.v1.ServiceAccount(foo, {metadata: {namespace: 'namespace-B'}}, {provider: k8sProvider})` . I would expect the serviceaccount to be created in `namespace-B` in the example above, but it actually gets created in `namespace-A`.

**Comment by geekflyer** [comment]
@adaniline-traderev, @Dominik-K, @mgoodness, @rosskevin, @casey-robertson, @AaronFriel, and @FraserWaters-GR since you thumps-upped #415 - do you have any opinion on which precedence behaviour makes more sense?

**Comment by FraserWaters-GR** [comment]
No strong opinion, changing it so resources override the provider sounds reasonable.

**Comment by rosskevin** [comment]
Programmatically this change makes sense.  A provider is more general or base level, a resource or component more specific.  Base should not override specialized.

**Comment by lblackstone** [comment]
I agree that having the resource take precedence makes sense if `namespace` is a "default" setting, but I designed it as an "override".

Currently, you can create multiple provider instances that point to the same cluster (using the same `kubeconfig`) if you want different override behavior for a subset of resources.

The specific use case I had in mind was for Helm charts and YAML manifests, where it's fairly common to want a different namespace than the default. One or more resources in those sources often have a namespace set, and I thought it made more sense to allow an easy override.

That being said, I'm interested in hearing use cases that would work better with a "default" rather than an "override". We could support both options if it makes sense.

**Comment by rosskevin** [comment]
> The specific use case I had in mind was for Helm charts and YAML manifests

I would expect to use a namespace transformation to change it on a helm chart or raw yaml.  That's just the path I was led to via docs etc that I have read.  I never even knew namespace was an option on provider.  <- I almost said `default namespace` right there, which is another of my userland expectation that provider namespace would not be an override.

I don't have a need here, but if I did and bumped into this behavior I would be caught by surprise.

**Comment by casey-robertson** [comment]
Agree with option 2. -- Resource namespace should take precedence over Provider namespace.  But also like @rosskevin feedback.  Thanks for investing time in this.

**Comment by geekflyer** [comment]
Just wanted to add: 
Afaik in other providers (in my case GCP) the behavior is 2. I.e. resource attributes take precedence over provider attributes. One such example is the `zone` property of the GCP provider: https://pulumi.io/reference/pkg/nodejs/pulumi/gcp/#ProviderArgs . This is probably why the k8s provider behavior came as especially surprising to me.

**Comment by hausdorff** [comment]
My 2 cents: you can think of a normal Pulumi Kubernetes app as having an implicit "default" Kubernetes provider. Resources that have a `.metadata.namespace` will "override" the namespace supplied by this implicit provider, and so it is very surprising that this behavior is different for first-class providers. If we don't change this now, it will bite approximately everyone in perpetuity.

So: my preference, personally, is to change this behavior so that the first-class providers are overridden when a `.metadata.namespace` is present. I'd also deprecate the current release to make it clear that you don't want to use it.

**Comment by lblackstone** [comment]
Thanks for all the feedback! I also discussed with @lukehoban and @hausdorff and we agreed to switch the behavior to be a "default" rather than an "override" (option 2).

I'll get this fixed shortly and the behavior will change in the `0.24.0` release of the provider.
