### ISSUE TITLE
Setting `.stringData` in `v1/Secret` results in Pulumi triggering a replace on every update

### ISSUE THREAD

**Issue by hausdorff** [pulumi/pulumi-kubernetes#653]
The following Pulumi program will faithfully report on every single `pulumi up` that the `stringData` member has been added to this object, and therefore the `Secret` has to be replaced.

```typescript
const testSecrets = new k8s.core.v1.Secret("test", {
    type: "Opaque",
    stringData: {
        "client-secret": "hello",
    },
});

```

Checking the live state of this, we see that `stringData` is missing. This is because the API server takes `stringData` and does the base64 conversion automatically, and uses that to populate the `data` field:

```yaml
apiVersion: v1
data:
  client-secret: aGVsbG8=
kind: Secret
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Secret","metadata":{"annotations":{"pulumi.com/autonamed":"true"},"labels":{"app.kubernetes.io/managed-by":"pulumi"},"name":"test-pyooxt59"},"stringData":{"client-secret":"hello"},"type":"Opaque"}
    pulumi.com/autonamed: "true"
  creationTimestamp: "2019-07-25T05:55:04Z"
  labels:
    app.kubernetes.io/managed-by: pulumi
  name: test-pyooxt59
  namespace: default
  resourceVersion: "366196"
  selfLink: /api/v1/namespaces/default/secrets/test-pyooxt59
  uid: bff1d5f7-aea0-11e9-aff3-42010a800013
type: Opaque
```

So this seems like a problem with the new diff logic generally.

**Comment by hausdorff** [comment]
cc @pgavlin

**Comment by pgavlin** [comment]
@hausdorff is this the case even with the newly-added dry run support?

**Comment by hausdorff** [comment]
Yes, this is built off master.

I think the problem is that when we fall back to a "normal" diff, we still don't actually do diffing the way we did before.

**Comment by pgavlin** [comment]
That’s correct, yes, and was intentional. We may need to add some special-case logic for cases like this where we intentionally differ from kubectl semantics.

**Comment by pgavlin** [comment]
Just out of curiosity, what does `kubectl diff` report if you deploy then diff equivalent YAML?

**Comment by hausdorff** [comment]
Makes sense.

Thoughts:

* This problem will be obvious, and will affect 100% of users using recent Pulumi with any version of Kubernetes before the current.
* This will also affect close to 100% of users who use the current version of Kubernetes, because the dry-run capability is turned off by default (for now) on all k8s-as-a-service platforms.
* `Diff` behavior now differs dramatically depending on the state of the API server, and we don't (shouldn't?) communicate this to the user.

**Comment by hausdorff** [comment]
> Just out of curiosity, what does `kubectl diff` report if you deploy then diff equivalent YAML?

Empty diff.

Also, what was the reason for not falling back to the old way of diffing if this fails? Too much work? Involves changes to pulumi/pulumi?

**Comment by pgavlin** [comment]
> This will also affect close to 100% of users who use the current version of Kubernetes, because the dry-run capability is turned off by default (for now) on all k8s-as-a-service platforms.

That does not appear to be the case: I have successfully used the new dry-run-enabled code with both GKE (on the test cluster) and EKS (via a fresh cluster).

> Also, what was the reason for not falling back to the old way of diffing if this fails? Too much work? Involves changes to pulumi/pulumi?

I don’t know what you mean by “fails” here. If dry run is not available, we now compute the diff from the merge patch rather than from the inputs. This allows us to a) better align with kubectl, and b) better detect diffs between the live state and the desired state, especially when the former has been mutated by tools that do not update the last applied config. Falling back to the old input-only logic would not address either point.

All that said, we should do what is best for users here. If we can’t make this work reasonably, we may need to compromise on these points.

**Comment by pgavlin** [comment]
> Empty diff.

So to be clear: if you deploy YAML with a secret that contains string data, then run `kubectl diff` with the same YAML, the output is empty?

**Comment by hausdorff** [comment]
> That does not appear to be the case: I have successfully used the new dry-run-enabled code with both GKE (on the test cluster) and EKS (via a fresh cluster).

How strange, I just did this with fresh GKE and found it was not enabled, which caused me to file [this PR](https://github.com/pulumi/pulumi-kubernetes/pull/654). So who knows.

> I don’t know what you mean by “fails” here. If dry run is not available, we now compute the diff from the merge patch rather than from the inputs. This allows us to a) better align with kubectl, and b) better detect diffs between the live state and the desired state, especially when the former has been mutated by tools that do not update the last applied config. Falling back to the old input-only logic would not address either point.
> 
> All that said, we should do what is best for users here. If we can’t make this work reasonably, we may need to compromise on these points.

Sorry, I'm confused... If the input has not changed, and we do input-only diffing, there should be no diff in this case, right?

> So to be clear: if you deploy YAML with a secret that contains string data, then run `kubectl diff` with the same YAML, the output is empty?

Yes, this appears to be true.

**Comment by pgavlin** [comment]
> Sorry, I'm confused... If the input has not changed, and we do input-only diffing, there should be no diff in this case, right?

Correct. We moved away from input-only diffing in order to better match kubectl and better detect diffs between the live and desired state. Returning to input-only diffing compromises those goals.

**Comment by pgavlin** [comment]
For what it's worth, I cannot repro this when running against the test CI cluster using a freshly-built provider with dry-run support: https://asciinema.org/a/w1apZRKrfa2LKj57yGvktsGNb

My guess is that this is only happening when we fall back to computing the diff without dry-run.

**Comment by pgavlin** [comment]
Indeed, I can only repro this if I disable the dry-run support.

**Comment by hausdorff** [comment]
Yes, I was saying this earlier—this diff will only register at all when we are falling back to the non-dry-run diff. I see now that you probably meant in your `kubectl diff` question whether this diff registers on clusters without dry-run. The answer is that it shows no diff on clusters with dry-run on (where we also give the correct answer).

> Correct. We moved away from input-only diffing in order to better match kubectl and better detect diffs between the live and desired state. Returning to input-only diffing compromises those goals.

Ok, makes sense.

I'm curious to hear if anyone thinks that either of the following are true:

* We can keep "live object aware diffing" and _also_ not have "perma-diffs".
* The impact of this is not substantial.

If either of those things is true then I think we can keep it as-is. I personally believe both of these are false. I still think we're doing the right thing when we have dry-run, but if both of these are indeed false, I think we'll need to "compromise", as you say.

**Comment by pgavlin** [comment]
> We can keep using "live object aware diffing" on old clusters and also not have "perma-diffs".

I do think that this is possible, but would entail some significant work (and may violate some k8s norms). My hypothesis is that the differences in the objects returned by the server occur due to conversions that are made between the patch we submit, the server's internal representation, and the object returned from the server. I _think_ that these conversions are all captured in the various `api` packages used by k8s. We may be able to reuse that code to perform normalization prior to diffing.

> The impact of this is not substantial.

I do believe that this could have substantial impact, especially for resources like `Secret` where we've added our own replacement semantics to certain changes.

> I think we'll need to "compromise", as you say, in the case of old clusters.

This is probably true. One of the more important scenarios w.r.t. detecting diffs by creating a patch is importing resources: without this, there's not much that we can do that is meaningful if there is no annotation that records the last applied configuration (and indeed, if that annotation is out-of-date, the imported resource's inputs are kind of a lie). However, getting that scenario right is less important than avoiding these sorts of spurious replaces.

Assuming we agree on the above, I feel okay about returning to input diffing where dry-run is not supported. Doing so may be a little bit more complicated than it seems, as we'll want to accommodate the detailed diff support added last milestone. Given that we would only be doing input diffs, this may be as simple as "don't send back a detailed diff" (in which case the CLI will render input diffs).
