### ISSUE TITLE
apiextensions apiVersion incorrect

### ISSUE THREAD

**Issue by protometa** [pulumi/pulumi-kubernetes#82]
When initializing a CustomResourceDefinition I get:

    error: Unable to fetch schema: Cluster does not support resource type 'apiextensions/v1beta1, Kind=CustomResourceDefinition'

Should the name here be `apiextensions.k8s.io/v1beta1` instead?

https://github.com/pulumi/pulumi-kubernetes/blob/2f1d4637c9b1c52cac6f8d25284e86f8cdc0cdb3/pack/nodejs/provider.ts#L362

**Comment by protometa** [comment]
It seems the swagger schema definition names are not a reliable source for these api group names.

**Comment by hausdorff** [comment]
Thanks for the report @protometa, you're exactly right, I'll have a fix in a PR later today.

In case someone else stumbles on the issue: the core problem is that the OpenAPI spec needs to be munged a bit to get an `apiVersion` that the API server understands. Some examples of exceptions are: `core/v1` -> `v1`, `rbac/v1` -> `rbac.authorization.k8s.io/v1`, and so on.

Sometimes this will manifest during an `update`, but it might also manifest during a `destroy`, because we're inferring `apiVersion` from the Pulumi URN for a resource, which is sometimes incorrectly populated here.
