### ISSUE TITLE
Add option to always delete and replace a whole Helm Chart if anything changes

### ISSUE THREAD

**Issue by 0x53A** [pulumi/pulumi-kubernetes#821]
My underlying issue is that I can't update my ``nginx-ingress`` Chart, it will fail with 

```
Plan apply failed: 1 error occurred:
        * the Kubernetes API server reported that "ingress-basic/nginx-ingress-controller" failed to fully initialize or become live: Service "nginx-ingress-controller" is invalid: spec.clusterIP: Invalid value: "": field is immutable
```

```js
const ingressNamespace = new k8s.core.v1.Namespace("ingress-basic", {
    metadata: {
        name: "ingress-basic"
    }
  }, { provider: k8sProvider });


// https://github.com/pulumi/pulumi-kubernetes/issues/217#issuecomment-459105809
function addNamespace(o) {
    if (o !== undefined) {
        if (o.metadata !== undefined) {
            o.metadata.namespace = ingressNamespace.metadata.name;
        } else {
            o.metadata = {namespace: ingressNamespace.metadata.name}
        }
    }
}


function fixAutomountServiceAccountToken(obj, opts){
    if (obj.kind === "ServiceAccount") {
        opts.automountServiceAccountToken = true;
    }

    if (obj.kind === "Pod") {
        obj.spec.automountServiceAccountToken = true;
    }
}

const ingressDeployment = new k8s.helm.v2.Chart("nginx-ingress", {
    repo: "stable",
    chart: "nginx-ingress",
    namespace: ingressNamespace.metadata.name,
    values: {
        controller: {
            replicaCount: 1,
            service: {
                externalTrafficPolicy: "Local",
                // https://github.com/terraform-providers/terraform-provider-azurerm/pull/4400
                // loadBalancerIP: ingressStaticIP.ipAddress
            }
        },
        rbac: { create: true },
    },
    transformations: [ addNamespace, fixAutomountServiceAccountToken ]
}, {
    providers: { kubernetes: k8sProvider },
    dependsOn: [ingressNamespace]
});
```

I'd hazard a guess that many helm charts have interconnected dependencies and might be brittle if only parts are re-deployed so I think it might make sense to add an option to the chart to always tear down and re-deploy the whole chart instead of individual parts.

I tried ``deleteBeforeReplace: true`` on the chart, but it didn't seem to change anything.

--------

Workaround: comment the chart out, ``pulumi up`` to destroy it, then undo and a second ``pulumi up``.

**Comment by hausdorff** [comment]
So, first, this case is a bug in the chart. They're setting `clusterIP` to be `""` inside the chart. Since the API server populates that field, subsequent applications of the chart will attempt to change this value back to `""`. But since this value is immutable, it can't be changed, and the application fails.

The work-around is to use `transformations` to set `clusterIP: undefined` if it's `""`.

As for the suggestion, to allow complete tear down of the chart every time: I have a strong reaction to that. :) I think this is quite invasive and to accept that this is necessary as a feature, I personally would want to see strong evidence that there are some things that _cannot_ be done in any other way. This, _prima facie_, does not seem to be the case here?

**Comment by 0x53A** [comment]
Hi thank you for the quick response!

I found https://github.com/helm/helm/issues/6378#issuecomment-532758606 with suggests to set ``controller.service.omitClusterIP`` and ``defaultBackend.service.omitClusterIP`` to true, but your suggestion with the transformation is probably even better (currently trying it out).

I'm just getting started with K8s and the whole cloud stuff, so I don't really have an informed opinion about best practices. I can see that it might be undesirable in Prod, but I think it could really simplify testing scenarios.
