### ISSUE TITLE
ctrl-c should usually cause an init failure

### ISSUE THREAD

**Issue by hausdorff** [pulumi/pulumi-kubernetes#89]
Currently if there is a looping initialization failure (_e.g._, application is continuously crashing and never becomes live) and the user presses ctrl-c Pulumi will:

* Tell the user that it's "cancelling" but then wait until the initialization timeout, which is often 5-10 minutes.
* Tell the user they can press ctrl-c again to cancel immediately, but it might "orphan resources". This usually leaves the stack in an "unknown state" which means that users have to do something like `stack export | stack import` and then delete the orphaned resource.

This greatly inhibits the inner loop development, which is overall very important to our scenarios.

A much better user experience (at least for Kubernetes) could be:

* Immediately kill the Kubernetes provider on ctrl-c
* If the object was not created successfully, report report a creation error.
* Otherwise report an initialization error, so that the engine can at least log the live object in checkpoint.

cc @lukehoban @joeduffy

**Comment by joeduffy** [comment]
There ought to be a work item in pulumi/pulumi for supporting true cancellation in the engine, including flowing it to plugins so that they are given the opportunity to participate.  That will be required to achieve this.  @swgillespie, @pgavlin, is there a work item already tracking this?  If not, let's file one.

**Comment by hausdorff** [comment]
Sweet, thanks. @joeduffy I think this is a really strong candidate for fixing in M16, because it seems to me that kube support will be not awesome until it's fixed. What do you think?

**Comment by hausdorff** [comment]
Hmm, the relevant pulumi/pulumi issues seem to be https://github.com/pulumi/pulumi/issues/1077 and https://github.com/pulumi/pulumi-service/issues/1405, but neither seems to handle this specific scenario. Correct me if I'm wrong?

**Comment by swgillespie** [comment]
No, I think you're right @hausdorff - I can't think of any issues off the top of my head that give the provider a chance to do something when cancellation is requested.

Does the kube provider keep track of which kubernetes API requests are in flight? I'm wondering if we could do something like create IDs for each provider operation and have providers (optionally) expose a `Cancel` RPC call that takes an ID and gives the provider a chance to cancel an operation with that ID. It'd always be legal for a provider to provide a no-op cancel since that's the existing provider behavior today.

**Comment by hausdorff** [comment]
Per offline discussion with @pgavlin and @swgillespie we have decided the following:

- We should add a `Cancel` function to the gRPC interface, the semantics of which are to signal (using Go's contexts) to all open requests that they should cancel. [_cf_., https://github.com/pulumi/pulumi/issues/1613]
- A single ctrl-c press should do what it does now, and additionally call `Cancel` on the resource provider. [_cf_., https://github.com/pulumi/pulumi/issues/1613]
- [ ] When `Cancel` is called on the Kubernetes controller, we should set a Go context on the provider base that signals to all open requests that a cancellation should occur; in turn, each of these should abort and return either creation or initialization failure back to the engine.
