### ISSUE TITLE
Cannot use PVC (eternal wait)

### ISSUE THREAD

**Issue by brandonkal** [pulumi/pulumi-kubernetes#895]
### Problem description

1. Pulumi Creates PVC
2. PVC reports:
```
Status: Pending
WaitForFirstConsumer
waiting for first consumer to be created before binding
```
3. Pulumi waits 5 minutes and then times out
```
resource pvc was successfully created, but the Kubernetes API server reported that it failed to fully initialize or become live: Timeout occurred polling for 'pvc'
```

Pulumi never creates the deployment because `pvc.mount('/data')` from `kubernetesx` is used. However, I do not believe this bug is specific to kx.

The problem is the pvc waits for a pod to request it while the pulumi controller waits for the pvc to no longer be pending, which of course won't happen unless pulumi is smart enough to create that deployment while the PVC is still pending.

**Comment by gregnr** [comment]
We are encountering this as well on AKS who's storage classes default to:
```yaml
volumeBindingMode: WaitForFirstConsumer
```

It's a chicken-and-egg scenario, where Pulumi doesn't want to create the `Deployment` until the `PersistentVolumeClaim` has been created (because the PVC name is a dependency), but Kubernetes doesn't want to create the `PersistentVolumeClaim` until a Pod is created, because of the above `volumeBindingMode`.

Our workaround was to create a custom `StorageClass` with 
```yaml
volumeBindingMode: Immediate
```

and manually set each PVC's storage class to the above custom one.

An alternative workaround would just be to ensure your `Deployment` doesn't depend on your `PVC` at all from Pulumi's perspective, ie. don't reference your `pvc.metadata.name` and instead hardcode the name. This of course assumes that the PVC name is known at build time.

**Comment by rvowles** [comment]
I'm hitting this on KinD as well.

**Comment by FP-Guitar** [comment]
Hitting this aswell on AKS

**Comment by FP-Guitar** [comment]
Found a feasible solution:
https://www.pulumi.com/blog/improving-kubernetes-management-with-pulumis-await-logic/
tl:dr
_To disable await logic for a selected resource, add the following annotation to the resource’s metadata: pulumi.com/skipAwait: "true"_
Add this to your PVC and pulumi will NOT wait for the resource to be ready getting you out of this Catch22

**Comment by isaac-mcfadyen** [comment]
Is there any update on this? This is a *major* issue to have happen by default and seems like a simple fix. Even Terraform has something more standardized: it's a dedicated field on the PVC instead of an ad-hoc annotation.

**Comment by ocervell** [comment]
This is definitely not fixed @mjeffryes

**Comment by mjeffryes** [comment]
> This is definitely not fixed [@mjeffryes](https://github.com/mjeffryes).
> 
> The current workaround by [@FP-Guitar](https://github.com/FP-Guitar) works until you declare a deployment that tries to wait for the Persistent Volume to be created...

@ocervell Would you mind filing a new version with the details of your repro case? It's possible that https://github.com/pulumi/pulumi-kubernetes/pull/3130 only fixes some causes this bug. Having a full program (and version information from `pulumi about`) will help us to understand what you're experiencing and try to help.
