### ISSUE TITLE
Helm charts with apiVersion=v2 (helm 3 and above compatible) fail to install

### ISSUE THREAD

**Issue by VRanga000** [pulumi/pulumi-kubernetes#954]
### Problem description

In pulumi/kubernetes, if a local helm chart with apiVersion=v2 is attempted to be installed, it fails with an error.

Code to install a helm chart (representative, not complete / verbatim):
```typescript
new kubernetes.helm.v2.Chart( "mycoolchart", {
    "path": "~/mycoolchartpath",
    "namespace": "mynamespace"
});
```

### Errors & Logs

```shell
    Error: Error: Command failed: helm template ~/vikas-testapp --name-template vikas-testapp-us-east-1 --values ~/vikas-testapp/values.yaml --values /tmp/tmp-300qLlS44toy6Ga.yaml --namespace reference-chart-dev
    Error: apiVersion 'v2' is not valid. The value must be "v1"
        at Chart.resources.allConfig.apply.cfg (/home/vikas/projects/janus-pulumi/node_modules/@pulumi/kubernetes/helm/v2/helm.js:120:23)
        at /home/vikas/projects/janus-pulumi/node_modules/@pulumi/kubernetes/node_modules/@pulumi/pulumi/output.js:220:35
        at Generator.next (<anonymous>)
        at /home/vikas/projects/janus-pulumi/node_modules/@pulumi/kubernetes/node_modules/@pulumi/pulumi/output.js:21:71
        at new Promise (<anonymous>)
        at __awaiter (/home/vikas/projects/janus-pulumi/node_modules/@pulumi/kubernetes/node_modules/@pulumi/pulumi/output.js:17:12)
        at applyHelperAsync (/home/vikas/projects/janus-pulumi/node_modules/@pulumi/kubernetes/node_modules/@pulumi/pulumi/output.js:199:12)
        at Promise.all.then (/home/vikas/projects/janus-pulumi/node_modules/@pulumi/kubernetes/node_modules/@pulumi/pulumi/output.js:179:65)
        at <anonymous>
```

### Affected product version(s)

@pulumi/kubernetes v 1.4.3

### Reproducing the issue

- Create a local helm chart
- In Chart.yaml, set apiVersion: v2
- Install the helm chart using pulumi code:
```typescript
import * as kubernetes from "@pulumi/kubernetes";

new kubernetes.helm.v2.Chart( "mycoolchart", {
    "path": "~/mycoolchartpath",
    "namespace": "mynamespace"
});
```

### Suggestions for a fix

Currently, there is a "quick fix" to support helm3 - by using "helm template --name-template" instead of "helm template --name" to generate the yaml for the chart - in order to support both helm 2 and helm 3. I suggest refactoring the helm package into a common package, and v2 and v3 subpackages. The common code could infer which one to use based on either:
- the apiVersion in the chart yaml and/or 
- the version of helm installed locally
and handle permutations of the above as needed.

Thank you for all the awesome work! I would not mind taking this on btw.

**Comment by lblackstone** [comment]
Hi @VRanga000, sorry for the delayed response. Currently, Pulumi's Helm support shells out to your local `helm` installation, so the SDK packages aren't the root cause of this error. 

Here's the relevant command from the NodeJS SDK: https://github.com/pulumi/pulumi-kubernetes/blob/bcdbc9e2b32594e6c2519a073d43b1030080cd5d/sdk/nodejs/helm/v2/helm.ts#L206

Our package naming hasn't been updated to reflect that it supports `v3`, but I think this should work as long as you have `helm3` installed on your system.

**Comment by VRanga000** [comment]
Thanks for the response, agreed. I was suggesting a way to support helm charts marked with apiVersion "v2" using helm 2 .. which is arguably an edge case, and maybe not a good idea to support anyways. WIll close this.

**Comment by vitobotta** [comment]
Hi @lblackstone, I am trying to install the Velero chart which is not compatible with Helm 3 yet, so I am specifying v2 with Pulumi. Installation fails because it skips unknown hook `crd-install`. So from what you said it seems that Pulumi uses my helm binary, which in my case is v3 since that's what I've been using for a while already. Is it possible to tell Pulumi the name of the binary to use? So I can still keep "helm" as the name of the binary for v3, and "helm2" for v2. So I would tell Pulumi to use "helm2". Is this possible? Thanks!

**Comment by lblackstone** [comment]
@vitobotta The problem isn't specific to the version of the Helm binary you're using; it's actually a lack of support for the `crd-install` hook. That feature is tracked in https://github.com/pulumi/pulumi-kubernetes/issues/1023

**Comment by vitobotta** [comment]
Thanks @lblackstone for the confirmation! I managed a workaround with some help in the Pulumi Slack. Thanks!
