### ISSUE TITLE
CI Failures related to EKS after 1.4.4 release

### ISSUE THREAD

**Issue by lblackstone** [pulumi/pulumi-kubernetes#958]
### Problem description

- Other: We've seen several CI failures in EKS following the release of 1.4.4. Need to determine if this is an issue with EKS, or the k8s provider.

### Errors & Logs

```
[ ks/nodejs/eks/examples/cluster ]     debug: Invoke RPC finished: tok=kubernetes:yaml:decode; err: Error: 2 UNKNOWN: invocation of kubernetes:yaml:decode returned an error: unable to load Kubernetes client configuration from kubeconfig file: invalid configuration: no configuration has been provided, resp: undefined
```

### Affected product version(s)
v1.4.4

### Reproducing the issue
Have not yet been able to reproduce the issue locally. Successfully created an EKS cluster, both with/without a dashboard.

**Comment by ergunozyurt** [comment]
This happens to us while targeting AKS with k8s provider that comes down as a stack reference. 

I couldn’t reproduce it locally and 
haven’t tested further. I think the k8s provider looks up for .kubeconfig file / kubecontext on running machine even it doesn’t use it to populate the object. That would explain how it passes through without an error locally because I had k8s context in place. I’ll let you know if I find some time to test my theory.

**Comment by lukehoban** [comment]
Another user reporting seeing this in https://github.com/pulumi/pulumi-kubernetes/issues/939#issuecomment-577412540.

**Comment by metral** [comment]
This is occurring with EKS CI when:

- no context is set, 
- no `~/.kube` dir exists, and
- no kubeconfig file set in `KUBECONFIG`

**Comment by lblackstone** [comment]
With the 1.4.5 release, I'm no longer seeing this error. Some of the EKS tests are still failing, but it appears to be unrelated to this error. I'm going to close this out since the EKS failures are already tracked in the linked issue.

**Comment by metral** [comment]
Wanted to say that as of 1.4.5. this error does appear to have subsided. Will keep an eye open on CI debug runs but should be g2g
